// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` (run from postinstall, on every `npm ci`) loads this file
// but never opens a database connection - it only reads the schema. Using
// Prisma's env() helper here made loading the config itself throw whenever
// DATABASE_URL wasn't set, which broke `generate` too, not just the commands
// that actually need a connection (`migrate deploy`, `db seed`, ...). Read
// the variable directly instead so a missing value only surfaces as a real,
// specific connection error from the command that actually needed it.
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
