import type { ActionPlanItem } from "@/types";

export const actionPlanItems: ActionPlanItem[] = [
  {
    id: "ACT-5001",
    title: "Complete SOC 2 Type II review for all tier-1 vendors",
    description: "Finish reviewing outstanding SOC 2 reports and close the RCSA action item.",
    sourceModule: "rcsa",
    sourceRef: "RCSA-4001",
    owner: "Layla Haddad",
    dueDate: "2026-08-15",
    status: "in-progress",
    progress: 60,
    dependencies: [],
    createdAt: "2026-07-15",
  },
  {
    id: "ACT-5002",
    title: "Correct wire transfer authorization role misconfiguration",
    description: "Reassign access roles so dual authorization is enforced on all outbound wires.",
    sourceModule: "incident",
    sourceRef: "INC-3021",
    owner: "Yusuf Karimi",
    dueDate: "2026-08-05",
    status: "in-progress",
    progress: 40,
    dependencies: [],
    createdAt: "2026-07-31",
  },
  {
    id: "ACT-5003",
    title: "Submit amended Hong Kong operating license renewal",
    description: "File the corrected renewal package with the local regulator.",
    sourceModule: "issue",
    sourceRef: "ISS-4003",
    owner: "Sara Al-Amin",
    dueDate: "2026-08-20",
    status: "not-started",
    progress: 0,
    dependencies: [],
    createdAt: "2026-07-22",
  },
  {
    id: "ACT-5004",
    title: "Qualify second alternate supplier for critical component",
    description: "Complete qualification audit and onboard the second alternate supplier.",
    sourceModule: "vendor",
    sourceRef: "VEN-6003",
    owner: "Daniel Osei",
    dueDate: "2026-09-01",
    status: "in-progress",
    progress: 35,
    dependencies: [{ actionId: "ACT-5003", title: "Submit amended Hong Kong operating license renewal" }],
    createdAt: "2026-07-10",
  },
  {
    id: "ACT-5005",
    title: "Install redundant cooling unit with automatic failover",
    description: "Complete facilities installation of the redundant HVAC unit for the server room.",
    sourceModule: "incident",
    sourceRef: "INC-3002",
    owner: "Marcus Chen",
    dueDate: "2026-07-10",
    status: "completed",
    progress: 100,
    dependencies: [],
    createdAt: "2026-07-01",
  },
  {
    id: "ACT-5006",
    title: "Deploy secondary data-center failover for payment processing",
    description: "Finish configuring automatic failover to the secondary data center.",
    sourceModule: "bcm",
    sourceRef: "BCP-7002",
    owner: "Priya Nair",
    dueDate: "2026-08-25",
    status: "in-progress",
    progress: 55,
    dependencies: [],
    createdAt: "2026-06-20",
  },
  {
    id: "ACT-5007",
    title: "Complete KSA data residency mapping for analytics workload",
    description: "Confirm the analytics workload is fully migrated to an in-kingdom region.",
    sourceModule: "issue",
    sourceRef: "ISS-4008",
    owner: "Yusuf Karimi",
    dueDate: "2026-08-12",
    status: "in-progress",
    progress: 80,
    dependencies: [],
    createdAt: "2026-07-19",
  },
  {
    id: "ACT-5008",
    title: "File amended quarterly regulatory disclosure",
    description: "Submit the amended filing and confirm regulator acknowledgment.",
    sourceModule: "compliance",
    sourceRef: "NCE-8002",
    owner: "Sara Al-Amin",
    dueDate: "2026-07-05",
    status: "completed",
    progress: 100,
    dependencies: [],
    createdAt: "2026-06-25",
  },
  {
    id: "ACT-5009",
    title: "Refresh forklift operator safety certification program",
    description: "Roll out updated safety certification training across all warehouse operators.",
    sourceModule: "incident",
    sourceRef: "INC-3016",
    owner: "Daniel Osei",
    dueDate: "2026-07-28",
    status: "not-started",
    progress: 0,
    dependencies: [],
    createdAt: "2026-07-26",
  },
  {
    id: "ACT-5010",
    title: "Negotiate higher payment processor rate limits",
    description: "Finalize contract amendment with the payment processor ahead of the next campaign.",
    sourceModule: "incident",
    sourceRef: "INC-3020",
    owner: "Priya Nair",
    dueDate: "2026-08-30",
    status: "not-started",
    progress: 0,
    dependencies: [{ actionId: "ACT-5006", title: "Deploy secondary data-center failover for payment processing" }],
    createdAt: "2026-07-29",
  },
  {
    id: "ACT-5011",
    title: "Establish quarterly regulatory horizon-scanning cadence",
    description: "Stand up a recurring process to monitor upcoming regulatory changes across APAC.",
    sourceModule: "rcsa",
    sourceRef: "RCSA-3011",
    owner: "Marcus Chen",
    dueDate: "2026-06-15",
    status: "completed",
    progress: 100,
    dependencies: [],
    createdAt: "2026-05-01",
  },
  {
    id: "ACT-5012",
    title: "Add legal sign-off gate to consent form template process",
    description: "Update the change-management workflow to require legal review before publishing.",
    sourceModule: "compliance",
    sourceRef: "NCE-8001",
    owner: "Layla Haddad",
    dueDate: "2026-07-01",
    status: "in-progress",
    progress: 70,
    dependencies: [],
    createdAt: "2026-06-10",
  },
];
