import type { ApprovalItem } from "@/types";

export const approvals: ApprovalItem[] = [
  {
    id: "APR-501",
    title: "Risk acceptance: legacy ERP end-of-life",
    type: "Risk Acceptance",
    requestedBy: "Priya Nair",
    submittedAt: "2026-07-28",
    dueDate: "2026-08-04",
    priority: "high",
    status: "pending",
  },
  {
    id: "APR-500",
    title: "New vendor onboarding: CloudSecure Inc.",
    type: "Third-Party Onboarding",
    requestedBy: "Marcus Chen",
    submittedAt: "2026-07-27",
    dueDate: "2026-08-02",
    priority: "medium",
    status: "pending",
  },
  {
    id: "APR-498",
    title: "Policy update: Remote Access Standard v4",
    type: "Policy Update",
    requestedBy: "Layla Haddad",
    submittedAt: "2026-07-25",
    dueDate: "2026-07-31",
    priority: "high",
    status: "pending",
  },
  {
    id: "APR-495",
    title: "Control exception: MFA rollout delay",
    type: "Control Exception",
    requestedBy: "Sara Al-Amin",
    submittedAt: "2026-07-20",
    dueDate: "2026-07-27",
    priority: "high",
    status: "approved",
  },
  {
    id: "APR-492",
    title: "Budget approval: Q3 compliance training",
    type: "Budget Request",
    requestedBy: "Omar Farouk",
    submittedAt: "2026-07-18",
    dueDate: "2026-07-24",
    priority: "low",
    status: "approved",
  },
  {
    id: "APR-488",
    title: "Risk acceptance: FX hedging threshold change",
    type: "Risk Acceptance",
    requestedBy: "Daniel Osei",
    submittedAt: "2026-07-12",
    dueDate: "2026-07-19",
    priority: "medium",
    status: "rejected",
  },
];
