import type { BusinessProcess, CrisisEvent } from "@/types";

export const businessProcesses: BusinessProcess[] = [
  {
    id: "BCP-7001",
    name: "Core Payment Processing",
    department: "Operations",
    criticality: "critical",
    mtd: "4 hours",
    rto: "2 hours",
    rpo: "15 minutes",
    recoveryStrategy: "Automatic failover to secondary data center with synchronous replication.",
    owner: "Priya Nair",
    lastTested: "2026-02-14",
    testResult: "passed",
    tests: [
      {
        id: "BCP-7001-T1",
        date: "2026-02-14",
        type: "Full Simulation",
        result: "passed",
        notes: "Failover completed within RTO; no data loss observed.",
      },
      {
        id: "BCP-7001-T2",
        date: "2025-08-10",
        type: "Full Simulation",
        result: "passed-with-observations",
        notes: "Failover succeeded but monitoring alerts were delayed by 6 minutes.",
      },
    ],
  },
  {
    id: "BCP-7002",
    name: "Payment Gateway Failover",
    department: "Technology",
    criticality: "critical",
    mtd: "2 hours",
    rto: "1 hour",
    rpo: "5 minutes",
    recoveryStrategy: "Automatic traffic rerouting to secondary payment processor.",
    owner: "Priya Nair",
    lastTested: "2026-01-20",
    testResult: "passed-with-observations",
    tests: [
      {
        id: "BCP-7002-T1",
        date: "2026-01-20",
        type: "Tabletop Exercise",
        result: "passed-with-observations",
        notes: "Rerouting configuration needs automation; manual step added latency.",
      },
    ],
  },
  {
    id: "BCP-7003",
    name: "Customer Contact Center Operations",
    department: "Operations",
    criticality: "high",
    mtd: "8 hours",
    rto: "4 hours",
    rpo: "1 hour",
    recoveryStrategy: "Redirect calls to backup contact center and enable remote agent access.",
    owner: "Daniel Osei",
    lastTested: "2025-11-05",
    testResult: "passed",
    tests: [
      {
        id: "BCP-7003-T1",
        date: "2025-11-05",
        type: "Walkthrough",
        result: "passed",
        notes: "Backup center reached full capacity within 3 hours.",
      },
    ],
  },
  {
    id: "BCP-7004",
    name: "Regulatory Reporting Submission",
    department: "Risk & Compliance",
    criticality: "high",
    mtd: "24 hours",
    rto: "12 hours",
    rpo: "4 hours",
    recoveryStrategy: "Manual submission process from backup workstation with offline data extracts.",
    owner: "Sara Al-Amin",
    lastTested: "2025-09-01",
    testResult: "not-tested",
    tests: [],
  },
  {
    id: "BCP-7005",
    name: "Core Banking Platform Availability",
    department: "Technology",
    criticality: "critical",
    mtd: "1 hour",
    rto: "30 minutes",
    rpo: "5 minutes",
    recoveryStrategy: "Active-active clustering across two availability zones.",
    owner: "Marcus Chen",
    lastTested: "2026-05-18",
    testResult: "passed",
    tests: [
      {
        id: "BCP-7005-T1",
        date: "2026-05-18",
        type: "Full Simulation",
        result: "passed",
        notes: "Zone failover completed in 4 minutes with zero downtime.",
      },
      {
        id: "BCP-7005-T2",
        date: "2025-11-20",
        type: "Full Simulation",
        result: "passed",
        notes: "Zone failover completed in 6 minutes.",
      },
    ],
  },
  {
    id: "BCP-7006",
    name: "Payroll Processing",
    department: "Human Resources",
    criticality: "medium",
    mtd: "48 hours",
    rto: "24 hours",
    rpo: "24 hours",
    recoveryStrategy: "Fallback to outsourced payroll bureau for one processing cycle.",
    owner: "Nadia Ibrahim",
    lastTested: "2025-12-10",
    testResult: "passed",
    tests: [
      {
        id: "BCP-7006-T1",
        date: "2025-12-10",
        type: "Call Tree Test",
        result: "passed",
        notes: "All key contacts reachable within 20 minutes.",
      },
    ],
  },
  {
    id: "BCP-7007",
    name: "Treasury FX Trading Desk",
    department: "Treasury",
    criticality: "high",
    mtd: "4 hours",
    rto: "2 hours",
    rpo: "30 minutes",
    recoveryStrategy: "Relocate trading desk staff to disaster recovery site with redundant trading terminals.",
    owner: "Omar Farouk",
    lastTested: "2026-03-22",
    testResult: "failed",
    tests: [
      {
        id: "BCP-7007-T1",
        date: "2026-03-22",
        type: "Full Simulation",
        result: "failed",
        notes: "Trading terminal licenses at DR site had expired; test aborted after 45 minutes.",
      },
    ],
  },
];

export const crisisEvents: CrisisEvent[] = [
  {
    id: "CRS-9001",
    title: "Regional power outage affecting primary data center",
    description: "Extended utility power outage triggered automatic failover to the secondary data center.",
    status: "resolved",
    triggeredAt: "2026-06-02T03:10:00",
    resolvedAt: "2026-06-02T05:40:00",
    affectedProcesses: ["BCP-7001", "BCP-7005"],
    responseTeam: ["Priya Nair", "Marcus Chen", "Yusuf Karimi"],
  },
  {
    id: "CRS-9002",
    title: "Severe weather warning for headquarters region",
    description: "National weather service issued a severe storm warning affecting the headquarters campus.",
    status: "contained",
    triggeredAt: "2026-07-28T14:00:00",
    resolvedAt: null,
    affectedProcesses: ["BCP-7003", "BCP-7006"],
    responseTeam: ["Daniel Osei", "Nadia Ibrahim"],
  },
  {
    id: "CRS-9003",
    title: "Trading desk disaster recovery site licensing lapse",
    description: "Disaster recovery trading terminal licenses expired, discovered during scheduled testing.",
    status: "active",
    triggeredAt: "2026-03-22T10:15:00",
    resolvedAt: null,
    affectedProcesses: ["BCP-7007"],
    responseTeam: ["Omar Farouk", "Yusuf Karimi"],
  },
];
