import type { ComplianceCalendarEntry, ComplianceObligation, NonComplianceEntry } from "@/types";

export const complianceObligations: ComplianceObligation[] = [
  {
    id: "OBL-8001",
    title: "SAMA Cyber Security Framework",
    type: "regulation",
    jurisdiction: "SAMA",
    owner: "Yusuf Karimi",
    status: "compliant",
    mappedRisks: ["RSK-1042", "RSK-1022"],
    mappedControls: ["CTL-2001", "CTL-2008"],
    lastReview: "2026-05-01",
    nextReview: "2026-11-01",
  },
  {
    id: "OBL-8002",
    title: "Data Protection & Privacy Policy",
    type: "policy",
    jurisdiction: "Internal Policy",
    owner: "Layla Haddad",
    status: "compliant",
    mappedRisks: ["RSK-1022"],
    mappedControls: ["CTL-2008"],
    lastReview: "2026-04-15",
    nextReview: "2026-10-15",
  },
  {
    id: "OBL-8003",
    title: "AML/CFT Transaction Monitoring Procedure",
    type: "procedure",
    jurisdiction: "SAMA",
    owner: "Marcus Chen",
    status: "partially-compliant",
    mappedRisks: ["RSK-1042"],
    mappedControls: ["CTL-2001"],
    lastReview: "2026-06-01",
    nextReview: "2026-08-15",
  },
  {
    id: "OBL-8004",
    title: "GDPR",
    type: "regulation",
    jurisdiction: "GDPR",
    owner: "Layla Haddad",
    status: "compliant",
    mappedRisks: ["RSK-1022"],
    mappedControls: ["CTL-2002"],
    lastReview: "2026-03-01",
    nextReview: "2026-09-01",
  },
  {
    id: "OBL-8005",
    title: "PCI DSS",
    type: "regulation",
    jurisdiction: "PCI DSS",
    owner: "Priya Nair",
    status: "compliant",
    mappedRisks: ["RSK-1019"],
    mappedControls: ["CTL-2003"],
    lastReview: "2026-04-10",
    nextReview: "2026-10-10",
  },
  {
    id: "OBL-8006",
    title: "Regional Licensing Renewal Procedure",
    type: "procedure",
    jurisdiction: "SAMA",
    owner: "Sara Al-Amin",
    status: "non-compliant",
    mappedRisks: ["RSK-1041"],
    mappedControls: ["CTL-2004"],
    lastReview: "2026-06-01",
    nextReview: "2026-08-05",
  },
  {
    id: "OBL-8007",
    title: "PDPL",
    type: "regulation",
    jurisdiction: "PDPL",
    owner: "Layla Haddad",
    status: "compliant",
    mappedRisks: ["RSK-1022"],
    mappedControls: ["CTL-2008"],
    lastReview: "2026-05-28",
    nextReview: "2026-11-28",
  },
  {
    id: "OBL-8008",
    title: "Basel III Capital Adequacy Procedure",
    type: "procedure",
    jurisdiction: "Basel Committee",
    owner: "Omar Farouk",
    status: "compliant",
    mappedRisks: ["RSK-1035"],
    mappedControls: ["CTL-2006"],
    lastReview: "2026-06-10",
    nextReview: "2026-09-10",
  },
  {
    id: "OBL-8009",
    title: "Business Continuity Management Policy",
    type: "policy",
    jurisdiction: "SAMA",
    owner: "Priya Nair",
    status: "not-assessed",
    mappedRisks: ["RSK-1019"],
    mappedControls: ["CTL-2009"],
    lastReview: "2025-08-01",
    nextReview: "2026-08-25",
  },
  {
    id: "OBL-8010",
    title: "Third-Party Risk Management Policy",
    type: "policy",
    jurisdiction: "SAMA",
    owner: "Marcus Chen",
    status: "partially-compliant",
    mappedRisks: ["RSK-1042", "RSK-1038"],
    mappedControls: ["CTL-2002", "CTL-2005"],
    lastReview: "2026-01-15",
    nextReview: "2026-08-30",
  },
];

export const nonComplianceEntries: NonComplianceEntry[] = [
  {
    id: "NCE-8001",
    obligationId: "OBL-8002",
    title: "Consent form disclosure clause gap",
    description: "Outdated consent form template omitted a required data-sharing disclosure clause.",
    severity: "low",
    identifiedDate: "2026-07-17",
    targetResolutionDate: "2026-07-18",
    status: "resolved",
    owner: "Layla Haddad",
  },
  {
    id: "NCE-8002",
    obligationId: "OBL-8003",
    title: "Transaction monitoring rule tuning behind schedule",
    description: "Quarterly rule threshold review has not been completed for the current cycle.",
    severity: "medium",
    identifiedDate: "2026-07-01",
    targetResolutionDate: "2026-08-15",
    status: "remediating",
    owner: "Marcus Chen",
  },
  {
    id: "NCE-8003",
    obligationId: "OBL-8006",
    title: "Hong Kong entity operating license lapsed",
    description: "A required local operating license renewal was filed after its expiry date.",
    severity: "high",
    identifiedDate: "2026-07-22",
    targetResolutionDate: "2026-08-20",
    status: "remediating",
    owner: "Sara Al-Amin",
  },
  {
    id: "NCE-8004",
    obligationId: "OBL-8010",
    title: "Vendor risk policy review overdue for two vendors",
    description: "Annual third-party risk policy re-attestation is outstanding for two tier-1 vendors.",
    severity: "medium",
    identifiedDate: "2026-07-05",
    targetResolutionDate: "2026-08-30",
    status: "open",
    owner: "Marcus Chen",
  },
];

export const complianceCalendar: ComplianceCalendarEntry[] = [
  { id: "CAL-1", title: "AML/CFT Transaction Monitoring Procedure review", date: "2026-08-15", type: "review" },
  { id: "CAL-2", title: "Hong Kong operating license renewal deadline", date: "2026-08-05", type: "renewal" },
  { id: "CAL-3", title: "SAMA quarterly compliance filing", date: "2026-08-31", type: "filing" },
  { id: "CAL-4", title: "Internal audit — third-party risk management", date: "2026-09-10", type: "audit" },
  { id: "CAL-5", title: "Business Continuity Management Policy review", date: "2026-08-25", type: "review" },
  { id: "CAL-6", title: "Third-Party Risk Management Policy re-attestation", date: "2026-08-30", type: "review" },
];
