import type { ControlItem } from "@/types";

export const controlItems: ControlItem[] = [
  {
    id: "CTL-2001",
    name: "Dual authorization for wire transfers above threshold",
    description:
      "All outbound wire transfers exceeding $50,000 require independent authorization from a second approver before release.",
    type: "preventive",
    frequency: "continuous",
    owner: "Marcus Chen",
    linkedRisks: ["RSK-1042", "RSK-1019"],
    linkedRegulations: ["SAMA Cyber Security Framework", "AML/CFT Law"],
    testingStatus: "passed",
    effectiveness: "highly-effective",
    lastReview: "2026-05-12",
    nextReview: "2026-11-12",
  },
  {
    id: "CTL-2002",
    name: "Quarterly vendor SOC 2 review",
    description:
      "Tier-1 vendor SOC 2 Type II reports are reviewed each quarter to confirm continued control effectiveness.",
    type: "detective",
    frequency: "quarterly",
    owner: "Layla Haddad",
    linkedRisks: ["RSK-1042"],
    linkedRegulations: ["GDPR", "PDPL"],
    testingStatus: "in-progress",
    effectiveness: "effective",
    lastReview: "2026-04-01",
    nextReview: "2026-07-01",
  },
  {
    id: "CTL-2003",
    name: "Automated reconciliation exception alerting",
    description:
      "Daily reconciliation jobs flag unmatched items above a materiality threshold for same-day investigation.",
    type: "detective",
    frequency: "daily",
    owner: "Priya Nair",
    linkedRisks: ["RSK-1019", "RSK-1030"],
    linkedRegulations: ["Basel III"],
    testingStatus: "passed",
    effectiveness: "effective",
    lastReview: "2026-06-20",
    nextReview: "2026-09-20",
  },
  {
    id: "CTL-2004",
    name: "Regulatory licensing tracker sign-off",
    description:
      "Regional compliance officers certify monthly that all operating licenses remain valid in each jurisdiction of operation.",
    type: "preventive",
    frequency: "monthly",
    owner: "Sara Al-Amin",
    linkedRisks: ["RSK-1041"],
    linkedRegulations: ["SAMA Cyber Security Framework"],
    testingStatus: "failed",
    effectiveness: "partially-effective",
    lastReview: "2026-06-01",
    nextReview: "2026-07-01",
  },
  {
    id: "CTL-2005",
    name: "Alternate supplier qualification program",
    description:
      "Maintains at least two qualified alternate suppliers for each single-source critical component category.",
    type: "corrective",
    frequency: "quarterly",
    owner: "Daniel Osei",
    linkedRisks: ["RSK-1038"],
    linkedRegulations: [],
    testingStatus: "not-tested",
    effectiveness: "partially-effective",
    lastReview: "2026-03-15",
    nextReview: "2026-09-15",
  },
  {
    id: "CTL-2006",
    name: "FX hedge ratio monitoring",
    description:
      "Treasury monitors the hedge ratio against the board-approved policy band and escalates breaches within 24 hours.",
    type: "detective",
    frequency: "weekly",
    owner: "Omar Farouk",
    linkedRisks: ["RSK-1035"],
    linkedRegulations: ["Basel III"],
    testingStatus: "passed",
    effectiveness: "highly-effective",
    lastReview: "2026-06-10",
    nextReview: "2026-09-10",
  },
  {
    id: "CTL-2007",
    name: "Legacy ERP compensating access review",
    description:
      "Manual quarterly access recertification for the legacy ERP platform pending full migration to the new core system.",
    type: "detective",
    frequency: "quarterly",
    owner: "Nadia Ibrahim",
    linkedRisks: ["RSK-1030"],
    linkedRegulations: ["SAMA Cyber Security Framework", "PCI DSS"],
    testingStatus: "in-progress",
    effectiveness: "partially-effective",
    lastReview: "2026-05-01",
    nextReview: "2026-08-01",
  },
  {
    id: "CTL-2008",
    name: "Data residency geo-fencing control",
    description:
      "Cloud workload policies restrict storage and processing of KSA customer data to approved in-kingdom regions.",
    type: "preventive",
    frequency: "continuous",
    owner: "Yusuf Karimi",
    linkedRisks: ["RSK-1022"],
    linkedRegulations: ["PDPL", "SAMA Cyber Security Framework"],
    testingStatus: "passed",
    effectiveness: "effective",
    lastReview: "2026-05-28",
    nextReview: "2026-11-28",
  },
  {
    id: "CTL-2009",
    name: "Secondary data-center failover drill",
    description:
      "Simulated failover of core payment processing to the secondary data center to validate recovery time objectives.",
    type: "corrective",
    frequency: "annual",
    owner: "Priya Nair",
    linkedRisks: ["RSK-1019"],
    linkedRegulations: ["SAMA BCM Framework"],
    testingStatus: "passed",
    effectiveness: "effective",
    lastReview: "2026-02-14",
    nextReview: "2027-02-14",
  },
  {
    id: "CTL-2010",
    name: "Engineering leadership succession plan",
    description:
      "Documented succession candidates and retention plans reviewed with HR leadership for key engineering roles.",
    type: "corrective",
    frequency: "annual",
    owner: "Nadia Ibrahim",
    linkedRisks: ["RSK-1027"],
    linkedRegulations: [],
    testingStatus: "not-tested",
    effectiveness: "ineffective",
    lastReview: "2025-11-01",
    nextReview: "2026-11-01",
  },
];
