import type { DocumentItem } from "@/types";

export const documents: DocumentItem[] = [
  {
    id: "DOC-201",
    name: "Enterprise Risk Management Framework v5.0",
    category: "Policy",
    owner: "Layla Haddad",
    version: "5.0",
    updatedAt: "2026-07-22",
    size: "2.4 MB",
    fileType: "pdf",
  },
  {
    id: "DOC-198",
    name: "Third-Party Risk Assessment Questionnaire",
    category: "Template",
    owner: "Marcus Chen",
    version: "2.1",
    updatedAt: "2026-07-18",
    size: "890 KB",
    fileType: "doc",
  },
  {
    id: "DOC-192",
    name: "Q2 2026 Board Risk Committee Minutes",
    category: "Governance",
    owner: "Sara Al-Amin",
    version: "1.0",
    updatedAt: "2026-07-15",
    size: "512 KB",
    fileType: "doc",
  },
  {
    id: "DOC-187",
    name: "Business Continuity Plan - APAC Region",
    category: "Policy",
    owner: "Daniel Osei",
    version: "3.4",
    updatedAt: "2026-07-10",
    size: "3.1 MB",
    fileType: "pdf",
  },
  {
    id: "DOC-180",
    name: "Annual Compliance Attestation Tracker",
    category: "Evidence",
    owner: "Priya Nair",
    version: "1.6",
    updatedAt: "2026-07-05",
    size: "1.2 MB",
    fileType: "xls",
  },
  {
    id: "DOC-175",
    name: "Cyber Incident Response Playbook",
    category: "Policy",
    owner: "Layla Haddad",
    version: "4.2",
    updatedAt: "2026-06-28",
    size: "1.8 MB",
    fileType: "pdf",
  },
  {
    id: "DOC-168",
    name: "Executive Risk Appetite Statement 2026",
    category: "Governance",
    owner: "Omar Farouk",
    version: "1.0",
    updatedAt: "2026-06-20",
    size: "640 KB",
    fileType: "ppt",
  },
  {
    id: "DOC-160",
    name: "Internal Audit Findings Register",
    category: "Evidence",
    owner: "Sara Al-Amin",
    version: "2.9",
    updatedAt: "2026-06-14",
    size: "980 KB",
    fileType: "xls",
  },
];

export const documentCategories = [
  "All",
  "Policy",
  "Template",
  "Governance",
  "Evidence",
];
