import type { IncidentItem } from "@/types";

export const incidents: IncidentItem[] = [
  {
    id: "INC-3021",
    title: "Unauthorized access attempt on customer portal",
    category: "Cybersecurity",
    severity: "critical",
    reportedBy: "Layla Haddad",
    reportedAt: "2026-07-30",
    status: "in-progress",
  },
  {
    id: "INC-3020",
    title: "Payment gateway outage during peak hours",
    category: "Operational",
    severity: "high",
    reportedBy: "Marcus Chen",
    reportedAt: "2026-07-29",
    status: "open",
  },
  {
    id: "INC-3018",
    title: "Data entry error in quarterly filing",
    category: "Compliance",
    severity: "medium",
    reportedBy: "Sara Al-Amin",
    reportedAt: "2026-07-27",
    status: "resolved",
  },
  {
    id: "INC-3016",
    title: "Warehouse safety near-miss incident",
    category: "Health & Safety",
    severity: "high",
    reportedBy: "Daniel Osei",
    reportedAt: "2026-07-26",
    status: "in-progress",
  },
  {
    id: "INC-3013",
    title: "Phishing email campaign targeting finance team",
    category: "Cybersecurity",
    severity: "high",
    reportedBy: "Priya Nair",
    reportedAt: "2026-07-24",
    status: "resolved",
  },
  {
    id: "INC-3010",
    title: "Vendor SLA breach on data center uptime",
    category: "Operational",
    severity: "medium",
    reportedBy: "Omar Farouk",
    reportedAt: "2026-07-21",
    status: "open",
  },
  {
    id: "INC-3006",
    title: "Minor data privacy consent form gap",
    category: "Compliance",
    severity: "low",
    reportedBy: "Layla Haddad",
    reportedAt: "2026-07-17",
    status: "resolved",
  },
  {
    id: "INC-3002",
    title: "Server room cooling system malfunction",
    category: "Technology",
    severity: "critical",
    reportedBy: "Marcus Chen",
    reportedAt: "2026-07-12",
    status: "resolved",
  },
];

export const incidentTrend = [
  { label: "Feb", value: 14 },
  { label: "Mar", value: 19 },
  { label: "Apr", value: 11 },
  { label: "May", value: 22 },
  { label: "Jun", value: 17 },
  { label: "Jul", value: 13 },
];
