import type { IncidentItem, IncidentStatus, IncidentRecord } from "@/types";

const LEGACY_STATUS: Record<IncidentRecord["status"], IncidentStatus> = {
  open: "open",
  investigating: "in-progress",
  resolved: "resolved",
  closed: "resolved",
};

export const incidentRecords: IncidentRecord[] = [
  {
    id: "INC-3021",
    title: "Unauthorized access attempt on customer portal",
    category: "Cybersecurity",
    department: "Technology",
    severity: "critical",
    status: "investigating",
    reportedBy: "Layla Haddad",
    reportedAt: "2026-07-30",
    rootCause:
      "Credential-stuffing attack exploited reused passwords from a third-party data breach.",
    impactDescription:
      "Three customer accounts were briefly accessed before automated anomaly detection locked the sessions.",
    impactLevel: "high",
    financialLoss: 0,
    regulatoryImpact: true,
    regulatoryImpactNotes: "Notifiable under SAMA Cyber Security Framework incident reporting rules.",
    assignedOwner: "Yusuf Karimi",
    investigationSummary:
      "SOC identified the source IP ranges and confirmed no lateral movement beyond the three accounts.",
    correctiveActions: [
      "Force password reset for all affected accounts",
      "Block identified source IP ranges at the WAF",
    ],
    preventiveActions: [
      "Enforce mandatory MFA for all customer portal logins",
      "Integrate breached-credential screening at signup",
    ],
    attachments: [
      {
        id: "INC-3021-A1",
        name: "SOC Investigation Report.pdf",
        type: "pdf",
        size: "1.4 MB",
        uploadedBy: "Yusuf Karimi",
        uploadedAt: "2026-07-31",
      },
    ],
    timeline: [
      {
        id: "INC-3021-T1",
        timestamp: "2026-07-30T09:14:00",
        actor: "System",
        action: "Detected",
        details: "Anomaly detection flagged unusual login velocity from new IP ranges.",
      },
      {
        id: "INC-3021-T2",
        timestamp: "2026-07-30T09:22:00",
        actor: "Layla Haddad",
        action: "Reported",
        details: "Incident logged and SOC engaged for investigation.",
      },
      {
        id: "INC-3021-T3",
        timestamp: "2026-07-31T14:00:00",
        actor: "Yusuf Karimi",
        action: "Investigating",
        details: "Root cause traced to credential stuffing; containment actions applied.",
      },
    ],
    closureApproved: false,
    closureApprovedBy: null,
    closureApprovedAt: null,
    updatedAt: "2026-07-31",
  },
  {
    id: "INC-3020",
    title: "Payment gateway outage during peak hours",
    category: "Operational",
    department: "Operations",
    severity: "high",
    status: "open",
    reportedBy: "Marcus Chen",
    reportedAt: "2026-07-29",
    rootCause: "Upstream payment processor API exceeded its rate limit during a promotional campaign.",
    impactDescription:
      "Approximately 12 minutes of degraded checkout availability affecting an estimated 3,400 transactions.",
    impactLevel: "high",
    financialLoss: 28000,
    regulatoryImpact: false,
    regulatoryImpactNotes: "",
    assignedOwner: "Priya Nair",
    investigationSummary: "Investigation in progress with the payment processor's technical account team.",
    correctiveActions: ["Failover to secondary payment processor during peak windows"],
    preventiveActions: ["Negotiate higher rate limits ahead of future promotional campaigns"],
    attachments: [],
    timeline: [
      {
        id: "INC-3020-T1",
        timestamp: "2026-07-29T18:02:00",
        actor: "Monitoring",
        action: "Detected",
        details: "Checkout error rate exceeded threshold and paged on-call operations.",
      },
      {
        id: "INC-3020-T2",
        timestamp: "2026-07-29T18:05:00",
        actor: "Marcus Chen",
        action: "Reported",
        details: "Incident opened and escalated to the payments engineering team.",
      },
    ],
    closureApproved: false,
    closureApprovedBy: null,
    closureApprovedAt: null,
    updatedAt: "2026-07-29",
  },
  {
    id: "INC-3018",
    title: "Data entry error in quarterly filing",
    category: "Compliance",
    department: "Risk & Compliance",
    severity: "medium",
    status: "closed",
    reportedBy: "Sara Al-Amin",
    reportedAt: "2026-07-27",
    rootCause: "Manual transcription error in the quarterly regulatory filing spreadsheet.",
    impactDescription: "Filed figures understated total exposure by 2%; corrected within the amendment window.",
    impactLevel: "low",
    financialLoss: 0,
    regulatoryImpact: true,
    regulatoryImpactNotes: "Amended filing submitted to SAMA within the permitted correction period.",
    assignedOwner: "Sara Al-Amin",
    investigationSummary: "Traced to a copy-paste error during the manual consolidation step.",
    correctiveActions: ["Submit amended filing", "Notify regulator of correction"],
    preventiveActions: ["Automate filing consolidation to remove manual transcription step"],
    attachments: [
      {
        id: "INC-3018-A1",
        name: "Amended Filing.pdf",
        type: "pdf",
        size: "620 KB",
        uploadedBy: "Sara Al-Amin",
        uploadedAt: "2026-07-28",
      },
    ],
    timeline: [
      {
        id: "INC-3018-T1",
        timestamp: "2026-07-27T10:00:00",
        actor: "Sara Al-Amin",
        action: "Reported",
        details: "Discrepancy identified during post-filing review.",
      },
      {
        id: "INC-3018-T2",
        timestamp: "2026-07-28T11:30:00",
        actor: "Sara Al-Amin",
        action: "Resolved",
        details: "Amended filing submitted and regulator notified.",
      },
      {
        id: "INC-3018-T3",
        timestamp: "2026-07-29T09:00:00",
        actor: "Layla Haddad",
        action: "Closed",
        details: "Closure approved after confirming regulator acknowledgment.",
      },
    ],
    closureApproved: true,
    closureApprovedBy: "Layla Haddad",
    closureApprovedAt: "2026-07-29",
    updatedAt: "2026-07-29",
  },
  {
    id: "INC-3016",
    title: "Warehouse safety near-miss incident",
    category: "Health & Safety",
    department: "Operations",
    severity: "high",
    status: "investigating",
    reportedBy: "Daniel Osei",
    reportedAt: "2026-07-26",
    rootCause: "Forklift operating in a pedestrian zone without adequate signage.",
    impactDescription: "No injuries; near-miss involving a warehouse associate.",
    impactLevel: "medium",
    financialLoss: 0,
    regulatoryImpact: false,
    regulatoryImpactNotes: "",
    assignedOwner: "Daniel Osei",
    investigationSummary: "Site safety team reviewing camera footage and interviewing witnesses.",
    correctiveActions: ["Install pedestrian barriers in the affected zone"],
    preventiveActions: ["Refresh forklift operator safety certification program"],
    attachments: [],
    timeline: [
      {
        id: "INC-3016-T1",
        timestamp: "2026-07-26T15:40:00",
        actor: "Daniel Osei",
        action: "Reported",
        details: "Near-miss reported by floor supervisor.",
      },
    ],
    closureApproved: false,
    closureApprovedBy: null,
    closureApprovedAt: null,
    updatedAt: "2026-07-26",
  },
  {
    id: "INC-3013",
    title: "Phishing email campaign targeting finance team",
    category: "Cybersecurity",
    department: "Finance",
    severity: "high",
    status: "closed",
    reportedBy: "Priya Nair",
    reportedAt: "2026-07-24",
    rootCause: "Targeted phishing email impersonating a senior executive requesting a wire transfer.",
    impactDescription: "No funds released; one employee reported the email before acting on it.",
    impactLevel: "low",
    financialLoss: 0,
    regulatoryImpact: false,
    regulatoryImpactNotes: "",
    assignedOwner: "Yusuf Karimi",
    investigationSummary: "Email headers traced to a spoofed external domain; blocked at the mail gateway.",
    correctiveActions: ["Block sender domain at the mail gateway"],
    preventiveActions: ["Run targeted phishing awareness refresher for finance staff"],
    attachments: [],
    timeline: [
      {
        id: "INC-3013-T1",
        timestamp: "2026-07-24T08:50:00",
        actor: "Priya Nair",
        action: "Reported",
        details: "Suspicious email forwarded to security team.",
      },
      {
        id: "INC-3013-T2",
        timestamp: "2026-07-24T09:30:00",
        actor: "Yusuf Karimi",
        action: "Resolved",
        details: "Sender domain blocked; no further attempts observed.",
      },
      {
        id: "INC-3013-T3",
        timestamp: "2026-07-25T10:00:00",
        actor: "Layla Haddad",
        action: "Closed",
        details: "Closure approved following awareness refresher completion.",
      },
    ],
    closureApproved: true,
    closureApprovedBy: "Layla Haddad",
    closureApprovedAt: "2026-07-25",
    updatedAt: "2026-07-25",
  },
  {
    id: "INC-3010",
    title: "Vendor SLA breach on data center uptime",
    category: "Operational",
    department: "Technology",
    severity: "medium",
    status: "open",
    reportedBy: "Omar Farouk",
    reportedAt: "2026-07-21",
    rootCause: "Cooling system fault at the vendor's secondary data center caused an unplanned outage window.",
    impactDescription: "Uptime SLA breached for the month; disaster-recovery systems were not required.",
    impactLevel: "medium",
    financialLoss: 5000,
    regulatoryImpact: false,
    regulatoryImpactNotes: "",
    assignedOwner: "Omar Farouk",
    investigationSummary: "Awaiting the vendor's root-cause report before finalizing service credits.",
    correctiveActions: ["Claim SLA service credits from vendor"],
    preventiveActions: ["Add secondary cooling redundancy requirement to next contract renewal"],
    attachments: [],
    timeline: [
      {
        id: "INC-3010-T1",
        timestamp: "2026-07-21T02:15:00",
        actor: "Monitoring",
        action: "Detected",
        details: "Data center uptime monitor recorded an outage window.",
      },
      {
        id: "INC-3010-T2",
        timestamp: "2026-07-21T09:00:00",
        actor: "Omar Farouk",
        action: "Reported",
        details: "Vendor notified and SLA breach logged.",
      },
    ],
    closureApproved: false,
    closureApprovedBy: null,
    closureApprovedAt: null,
    updatedAt: "2026-07-21",
  },
  {
    id: "INC-3006",
    title: "Minor data privacy consent form gap",
    category: "Compliance",
    department: "Legal",
    severity: "low",
    status: "closed",
    reportedBy: "Layla Haddad",
    reportedAt: "2026-07-17",
    rootCause: "Outdated consent form template omitted a required data-sharing disclosure clause.",
    impactDescription: "Affected 40 customer sign-ups over a two-week period before the template was corrected.",
    impactLevel: "low",
    financialLoss: 0,
    regulatoryImpact: true,
    regulatoryImpactNotes: "Logged for PDPL records; no complaints received from affected customers.",
    assignedOwner: "Layla Haddad",
    investigationSummary: "Confirmed the gap was limited to the single onboarding form template.",
    correctiveActions: ["Update consent form template", "Re-issue disclosure to affected sign-ups"],
    preventiveActions: ["Add legal sign-off gate to the form template change process"],
    attachments: [],
    timeline: [
      {
        id: "INC-3006-T1",
        timestamp: "2026-07-17T13:00:00",
        actor: "Layla Haddad",
        action: "Reported",
        details: "Gap identified during a routine privacy control review.",
      },
      {
        id: "INC-3006-T2",
        timestamp: "2026-07-18T10:00:00",
        actor: "Layla Haddad",
        action: "Closed",
        details: "Template corrected and affected sign-ups re-issued disclosure.",
      },
    ],
    closureApproved: true,
    closureApprovedBy: "Marcus Chen",
    closureApprovedAt: "2026-07-18",
    updatedAt: "2026-07-18",
  },
  {
    id: "INC-3002",
    title: "Server room cooling system malfunction",
    category: "Technology",
    department: "Technology",
    severity: "critical",
    status: "closed",
    reportedBy: "Marcus Chen",
    reportedAt: "2026-07-12",
    rootCause: "HVAC compressor failure in the primary on-premises server room.",
    impactDescription: "Automated thermal shutdown of two non-critical application servers; no data loss.",
    impactLevel: "medium",
    financialLoss: 12500,
    regulatoryImpact: false,
    regulatoryImpactNotes: "",
    assignedOwner: "Marcus Chen",
    investigationSummary: "Facilities confirmed compressor failure; replaced under vendor warranty.",
    correctiveActions: ["Replace HVAC compressor", "Restore affected application servers"],
    preventiveActions: ["Install redundant cooling unit with automatic failover"],
    attachments: [
      {
        id: "INC-3002-A1",
        name: "Facilities Incident Report.pdf",
        type: "pdf",
        size: "890 KB",
        uploadedBy: "Marcus Chen",
        uploadedAt: "2026-07-13",
      },
    ],
    timeline: [
      {
        id: "INC-3002-T1",
        timestamp: "2026-07-12T03:20:00",
        actor: "Monitoring",
        action: "Detected",
        details: "Server room temperature exceeded safe operating threshold.",
      },
      {
        id: "INC-3002-T2",
        timestamp: "2026-07-12T04:00:00",
        actor: "Marcus Chen",
        action: "Reported",
        details: "Facilities and IT operations engaged for emergency response.",
      },
      {
        id: "INC-3002-T3",
        timestamp: "2026-07-14T09:00:00",
        actor: "Layla Haddad",
        action: "Closed",
        details: "Closure approved after redundant cooling unit installed.",
      },
    ],
    closureApproved: true,
    closureApprovedBy: "Layla Haddad",
    closureApprovedAt: "2026-07-14",
    updatedAt: "2026-07-14",
  },
];

export const incidents: IncidentItem[] = incidentRecords.map((incident) => ({
  id: incident.id,
  title: incident.title,
  category: incident.category,
  severity: incident.severity,
  reportedBy: incident.reportedBy,
  reportedAt: incident.reportedAt,
  status: LEGACY_STATUS[incident.status],
}));

export const incidentTrend = [
  { label: "Feb", value: 14 },
  { label: "Mar", value: 19 },
  { label: "Apr", value: 11 },
  { label: "May", value: 22 },
  { label: "Jun", value: 17 },
  { label: "Jul", value: 13 },
];
