import type { IssueItem } from "@/types";

export const issueItems: IssueItem[] = [
  {
    id: "ISS-4001",
    title: "SOC 2 review evidence incomplete for two tier-1 vendors",
    description:
      "Two tier-1 vendors have not yet submitted current SOC 2 Type II reports for the annual review cycle.",
    source: "rcsa",
    relatedRiskId: "RSK-1042",
    relatedIncidentId: null,
    priority: "high",
    status: "in-progress",
    owner: "Layla Haddad",
    dueDate: "2026-08-15",
    escalated: false,
    escalatedTo: null,
    escalatedAt: null,
    comments: [
      {
        id: "ISS-4001-C1",
        author: "Layla Haddad",
        message: "Reached out to both vendors requesting updated reports.",
        createdAt: "2026-07-20",
      },
    ],
    closureEvidence: null,
    createdAt: "2026-07-15",
    updatedAt: "2026-07-20",
  },
  {
    id: "ISS-4002",
    title: "Wire transfer dual-authorization bypassed in one branch",
    description:
      "A single wire transfer was released without the required second approver due to a system access misconfiguration.",
    source: "incident",
    relatedRiskId: "RSK-1042",
    relatedIncidentId: "INC-3021",
    priority: "critical",
    status: "escalated",
    owner: "Marcus Chen",
    dueDate: "2026-08-05",
    escalated: true,
    escalatedTo: "Layla Haddad",
    escalatedAt: "2026-07-31",
    comments: [
      {
        id: "ISS-4002-C1",
        author: "Marcus Chen",
        message: "Access misconfiguration identified; correcting role assignments now.",
        createdAt: "2026-07-30",
      },
      {
        id: "ISS-4002-C2",
        author: "Layla Haddad",
        message: "Escalating given regulatory notification exposure.",
        createdAt: "2026-07-31",
      },
    ],
    closureEvidence: null,
    createdAt: "2026-07-30",
    updatedAt: "2026-07-31",
  },
  {
    id: "ISS-4003",
    title: "Regulatory licensing gap in Hong Kong entity",
    description: "A required local operating license renewal was filed after its expiry date.",
    source: "regulatory",
    relatedRiskId: "RSK-1041",
    relatedIncidentId: null,
    priority: "high",
    status: "open",
    owner: "Sara Al-Amin",
    dueDate: "2026-08-20",
    escalated: false,
    escalatedTo: null,
    escalatedAt: null,
    comments: [],
    closureEvidence: null,
    createdAt: "2026-07-22",
    updatedAt: "2026-07-22",
  },
  {
    id: "ISS-4004",
    title: "Reconciliation exception aging beyond policy threshold",
    description: "Twelve reconciliation exceptions have remained open for more than 30 days.",
    source: "audit",
    relatedRiskId: "RSK-1019",
    relatedIncidentId: null,
    priority: "medium",
    status: "in-progress",
    owner: "Priya Nair",
    dueDate: "2026-08-10",
    escalated: false,
    escalatedTo: null,
    escalatedAt: null,
    comments: [
      {
        id: "ISS-4004-C1",
        author: "Priya Nair",
        message: "Cleared five of the twelve exceptions; remainder pending counterparty confirmation.",
        createdAt: "2026-07-28",
      },
    ],
    closureEvidence: null,
    createdAt: "2026-07-18",
    updatedAt: "2026-07-28",
  },
  {
    id: "ISS-4005",
    title: "Alternate supplier qualification behind schedule",
    description: "Qualification of the second alternate supplier has slipped past the target date.",
    source: "self-identified",
    relatedRiskId: "RSK-1038",
    relatedIncidentId: null,
    priority: "medium",
    status: "open",
    owner: "Daniel Osei",
    dueDate: "2026-09-01",
    escalated: false,
    escalatedTo: null,
    escalatedAt: null,
    comments: [],
    closureEvidence: null,
    createdAt: "2026-07-10",
    updatedAt: "2026-07-10",
  },
  {
    id: "ISS-4006",
    title: "FX hedge ratio briefly outside policy band",
    description: "Hedge ratio dipped 3 points below the board-approved policy band for two trading days.",
    source: "self-identified",
    relatedRiskId: "RSK-1035",
    relatedIncidentId: null,
    priority: "low",
    status: "resolved",
    owner: "Omar Farouk",
    dueDate: "2026-07-15",
    escalated: false,
    escalatedTo: null,
    escalatedAt: null,
    comments: [
      {
        id: "ISS-4006-C1",
        author: "Omar Farouk",
        message: "Hedge ratio restored to policy band same day; monitoring alert threshold tightened.",
        createdAt: "2026-07-14",
      },
    ],
    closureEvidence: null,
    createdAt: "2026-07-12",
    updatedAt: "2026-07-14",
  },
  {
    id: "ISS-4007",
    title: "Legacy ERP access recertification overdue",
    description: "Quarterly access recertification for the legacy ERP platform was not completed on schedule.",
    source: "audit",
    relatedRiskId: "RSK-1030",
    relatedIncidentId: null,
    priority: "medium",
    status: "closed",
    owner: "Nadia Ibrahim",
    dueDate: "2026-06-30",
    escalated: false,
    escalatedTo: null,
    escalatedAt: null,
    comments: [
      {
        id: "ISS-4007-C1",
        author: "Nadia Ibrahim",
        message: "Recertification completed for all 84 accounts; three access revocations processed.",
        createdAt: "2026-06-28",
      },
    ],
    closureEvidence:
      "Signed recertification log confirming all 84 legacy ERP accounts reviewed; 3 revoked, 81 retained.",
    createdAt: "2026-06-15",
    updatedAt: "2026-06-28",
  },
  {
    id: "ISS-4008",
    title: "Data residency mapping incomplete for one workload",
    description: "One analytics workload's data residency mapping was not yet confirmed as KSA-only.",
    source: "management-review",
    relatedRiskId: "RSK-1022",
    relatedIncidentId: null,
    priority: "high",
    status: "in-progress",
    owner: "Yusuf Karimi",
    dueDate: "2026-08-12",
    escalated: false,
    escalatedTo: null,
    escalatedAt: null,
    comments: [
      {
        id: "ISS-4008-C1",
        author: "Yusuf Karimi",
        message: "Workload migrated to in-kingdom region; awaiting final confirmation from cloud team.",
        createdAt: "2026-07-29",
      },
    ],
    closureEvidence: null,
    createdAt: "2026-07-19",
    updatedAt: "2026-07-29",
  },
];
