import type { KriItem } from "@/types";

export const kris: KriItem[] = [
  {
    id: "KRI-01",
    name: "Critical vulnerability remediation time",
    category: "Cybersecurity",
    current: 4.2,
    target: 5,
    unit: "days",
    trend: [6.1, 5.8, 5.2, 4.9, 4.6, 4.2],
    status: "on-track",
  },
  {
    id: "KRI-02",
    name: "Regulatory findings past due",
    category: "Compliance",
    current: 7,
    target: 3,
    unit: "items",
    trend: [2, 3, 4, 5, 6, 7],
    status: "breached",
  },
  {
    id: "KRI-03",
    name: "Employee attrition rate",
    category: "Human Capital",
    current: 11.4,
    target: 12,
    unit: "%",
    trend: [13.2, 12.8, 12.1, 11.9, 11.6, 11.4],
    status: "on-track",
  },
  {
    id: "KPI-04",
    name: "Third-party risk assessments completed",
    category: "Operational",
    current: 82,
    target: 95,
    unit: "%",
    trend: [70, 74, 76, 78, 80, 82],
    status: "at-risk",
  },
  {
    id: "KPI-05",
    name: "Incident mean time to resolution",
    category: "Operational",
    current: 6.8,
    target: 8,
    unit: "hrs",
    trend: [9.5, 8.9, 8.1, 7.6, 7.1, 6.8],
    status: "on-track",
  },
  {
    id: "KRI-06",
    name: "Customer concentration ratio",
    category: "Strategic",
    current: 38,
    target: 30,
    unit: "%",
    trend: [30, 32, 34, 35, 37, 38],
    status: "at-risk",
  },
  {
    id: "KPI-07",
    name: "Control self-assessment coverage",
    category: "Compliance",
    current: 96,
    target: 90,
    unit: "%",
    trend: [88, 89, 91, 93, 95, 96],
    status: "on-track",
  },
  {
    id: "KRI-08",
    name: "Unplanned system downtime",
    category: "Technology",
    current: 3.1,
    target: 2,
    unit: "hrs/mo",
    trend: [1.4, 1.8, 2.2, 2.6, 2.9, 3.1],
    status: "breached",
  },
];
