import type { RcsaAssessment, RcsaCycle } from "@/types";

export const rcsaCycles: RcsaCycle[] = [
  {
    id: "RCSA-2026-Q3",
    name: "Q3 2026 Enterprise RCSA",
    period: "Q3 2026",
    status: "in-progress",
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    businessUnitsCount: 8,
    assessmentsCount: 6,
    completionRate: 62,
  },
  {
    id: "RCSA-2026-Q2",
    name: "Q2 2026 Enterprise RCSA",
    period: "Q2 2026",
    status: "closed",
    startDate: "2026-04-01",
    endDate: "2026-06-30",
    businessUnitsCount: 8,
    assessmentsCount: 8,
    completionRate: 100,
  },
  {
    id: "RCSA-2026-Q1",
    name: "Q1 2026 Enterprise RCSA",
    period: "Q1 2026",
    status: "closed",
    startDate: "2026-01-01",
    endDate: "2026-03-31",
    businessUnitsCount: 7,
    assessmentsCount: 7,
    completionRate: 100,
  },
  {
    id: "RCSA-2026-Q4",
    name: "Q4 2026 Enterprise RCSA",
    period: "Q4 2026",
    status: "planning",
    startDate: "2026-10-01",
    endDate: "2026-12-31",
    businessUnitsCount: 8,
    assessmentsCount: 0,
    completionRate: 0,
  },
];

export const rcsaAssessments: RcsaAssessment[] = [
  {
    id: "RCSA-4001",
    cycleId: "RCSA-2026-Q3",
    businessUnit: "Retail Banking",
    process: "Account Opening",
    subProcess: "Customer Identity Verification",
    owner: "Marcus Chen",
    assessor: "Sara Al-Amin",
    status: "under-review",
    overallInherentRisk: "high",
    overallResidualRisk: "medium",
    actionRecommendations: [
      "Automate identity document verification with OCR + liveness check",
      "Introduce dual sign-off for manually reviewed applications",
    ],
    submittedAt: "2026-07-22",
    approvedAt: null,
    approvedBy: null,
    updatedAt: "2026-07-24",
    risks: [
      {
        id: "RCSA-4001-R1",
        description: "Fraudulent identity documents accepted during onboarding",
        category: "Operational",
        inherentLikelihood: 4,
        inherentImpact: 4,
        inherentRisk: "high",
        residualLikelihood: 2,
        residualImpact: 4,
        residualRisk: "medium",
        controls: [
          {
            id: "RCSA-4001-C1",
            name: "Automated document authentication (OCR + hologram check)",
            type: "preventive",
            effectiveness: "effective",
          },
          {
            id: "RCSA-4001-C2",
            name: "Secondary manual review for flagged applications",
            type: "detective",
            effectiveness: "partially-effective",
          },
        ],
        recommendation: "Upgrade OCR engine to support GCC national ID formats natively.",
      },
      {
        id: "RCSA-4001-R2",
        description: "Incomplete KYC data captured at account opening",
        category: "Compliance",
        inherentLikelihood: 3,
        inherentImpact: 3,
        inherentRisk: "medium",
        residualLikelihood: 2,
        residualImpact: 2,
        residualRisk: "low",
        controls: [
          {
            id: "RCSA-4001-C3",
            name: "Mandatory field validation in onboarding workflow",
            type: "preventive",
            effectiveness: "highly-effective",
          },
        ],
        recommendation: "No further action - control operating effectively.",
      },
    ],
    reviewHistory: [
      {
        id: "RCSA-4001-REV1",
        reviewer: "Priya Nair",
        date: "2026-07-23",
        comment: "Residual risk on identity fraud remains elevated - request quantified remediation timeline before approval.",
        decision: "changes-requested",
      },
    ],
    versions: [
      {
        id: "RCSA-4001-V1",
        version: 1,
        editedBy: "Sara Al-Amin",
        editedAt: "2026-07-22",
        summary: "Initial self-assessment submitted",
      },
    ],
  },
  {
    id: "RCSA-4002",
    cycleId: "RCSA-2026-Q3",
    businessUnit: "Corporate Banking",
    process: "Loan Origination",
    subProcess: "Credit Approval Authority",
    owner: "Daniel Osei",
    assessor: "Sara Al-Amin",
    status: "approved",
    overallInherentRisk: "high",
    overallResidualRisk: "low",
    actionRecommendations: [
      "Formalize delegated authority matrix in the credit policy manual",
    ],
    submittedAt: "2026-07-10",
    approvedAt: "2026-07-18",
    approvedBy: "Layla Haddad",
    updatedAt: "2026-07-18",
    risks: [
      {
        id: "RCSA-4002-R1",
        description: "Credit approved beyond delegated authority limits",
        category: "Financial",
        inherentLikelihood: 3,
        inherentImpact: 5,
        inherentRisk: "high",
        residualLikelihood: 1,
        residualImpact: 3,
        residualRisk: "low",
        controls: [
          {
            id: "RCSA-4002-C1",
            name: "System-enforced delegated authority limits",
            type: "preventive",
            effectiveness: "highly-effective",
          },
          {
            id: "RCSA-4002-C2",
            name: "Quarterly exception report review by Credit Committee",
            type: "detective",
            effectiveness: "effective",
          },
        ],
        recommendation: "Maintain current controls; document authority matrix formally.",
      },
    ],
    reviewHistory: [
      {
        id: "RCSA-4002-REV1",
        reviewer: "Layla Haddad",
        date: "2026-07-18",
        comment: "Well-controlled process. Approved.",
        decision: "approved",
      },
    ],
    versions: [
      {
        id: "RCSA-4002-V1",
        version: 1,
        editedBy: "Daniel Osei",
        editedAt: "2026-07-10",
        summary: "Initial self-assessment submitted",
      },
    ],
  },
  {
    id: "RCSA-4003",
    cycleId: "RCSA-2026-Q3",
    businessUnit: "Treasury",
    process: "FX Trading",
    subProcess: "Trade Confirmation & Settlement",
    owner: "Omar Farouk",
    assessor: "Marcus Chen",
    status: "self-assessed",
    overallInherentRisk: "critical",
    overallResidualRisk: "medium",
    actionRecommendations: [
      "Implement straight-through processing for confirmed trades under threshold",
      "Increase settlement reconciliation frequency to intraday",
    ],
    submittedAt: "2026-07-28",
    approvedAt: null,
    approvedBy: null,
    updatedAt: "2026-07-28",
    risks: [
      {
        id: "RCSA-4003-R1",
        description: "Unmatched FX trade confirmations leading to settlement failure",
        category: "Operational",
        inherentLikelihood: 4,
        inherentImpact: 5,
        inherentRisk: "critical",
        residualLikelihood: 3,
        residualImpact: 3,
        residualRisk: "medium",
        controls: [
          {
            id: "RCSA-4003-C1",
            name: "End-of-day trade matching against counterparty confirmations",
            type: "detective",
            effectiveness: "partially-effective",
          },
        ],
        recommendation: "Move to intraday matching for trades above $5M notional.",
      },
      {
        id: "RCSA-4003-R2",
        description: "Manual override of dealing limits during volatile markets",
        category: "Financial",
        inherentLikelihood: 3,
        inherentImpact: 4,
        inherentRisk: "high",
        residualLikelihood: 2,
        residualImpact: 3,
        residualRisk: "medium",
        controls: [
          {
            id: "RCSA-4003-C2",
            name: "Dual authorization required for limit overrides",
            type: "preventive",
            effectiveness: "effective",
          },
        ],
        recommendation: "Add automated alert to Risk when overrides exceed 3 per week.",
      },
    ],
    reviewHistory: [],
    versions: [
      {
        id: "RCSA-4003-V1",
        version: 1,
        editedBy: "Omar Farouk",
        editedAt: "2026-07-28",
        summary: "Initial self-assessment submitted",
      },
    ],
  },
  {
    id: "RCSA-4004",
    cycleId: "RCSA-2026-Q3",
    businessUnit: "Technology & Digital",
    process: "Change Management",
    subProcess: "Production Deployment Approval",
    owner: "Nadia Ibrahim",
    assessor: "Marcus Chen",
    status: "draft",
    overallInherentRisk: "high",
    overallResidualRisk: "medium",
    actionRecommendations: [],
    submittedAt: null,
    approvedAt: null,
    approvedBy: null,
    updatedAt: "2026-07-15",
    risks: [
      {
        id: "RCSA-4004-R1",
        description: "Unauthorized code deployed to production without change ticket",
        category: "Technology",
        inherentLikelihood: 3,
        inherentImpact: 4,
        inherentRisk: "high",
        residualLikelihood: 2,
        residualImpact: 3,
        residualRisk: "medium",
        controls: [
          {
            id: "RCSA-4004-C1",
            name: "CI/CD pipeline gated by approved change ticket ID",
            type: "preventive",
            effectiveness: "effective",
          },
        ],
        recommendation: "Draft in progress - assessment not yet finalized.",
      },
    ],
    reviewHistory: [],
    versions: [
      {
        id: "RCSA-4004-V1",
        version: 1,
        editedBy: "Nadia Ibrahim",
        editedAt: "2026-07-15",
        summary: "Draft created",
      },
    ],
  },
  {
    id: "RCSA-4005",
    cycleId: "RCSA-2026-Q3",
    businessUnit: "Operations",
    process: "Payment Processing",
    subProcess: "Outbound Wire Transfer Authorization",
    owner: "Fatima Al-Zahra",
    assessor: "Sara Al-Amin",
    status: "rejected",
    overallInherentRisk: "critical",
    overallResidualRisk: "high",
    actionRecommendations: [
      "Introduce real-time sanctions screening before release",
      "Reduce maker-checker exception threshold from $250K to $100K",
    ],
    submittedAt: "2026-07-05",
    approvedAt: null,
    approvedBy: null,
    updatedAt: "2026-07-12",
    risks: [
      {
        id: "RCSA-4005-R1",
        description: "Sanctioned entity payment released without adequate screening",
        category: "Compliance",
        inherentLikelihood: 3,
        inherentImpact: 5,
        inherentRisk: "critical",
        residualLikelihood: 3,
        residualImpact: 5,
        residualRisk: "critical",
        controls: [
          {
            id: "RCSA-4005-C1",
            name: "Batch (end-of-day) sanctions list screening",
            type: "detective",
            effectiveness: "ineffective",
          },
        ],
        recommendation: "Escalate: current control is not adequate for a critical residual risk.",
      },
    ],
    reviewHistory: [
      {
        id: "RCSA-4005-REV1",
        reviewer: "Layla Haddad",
        date: "2026-07-12",
        comment: "Residual risk unacceptable at current rating with only a batch screening control. Rejected - resubmit with a real-time screening remediation plan and target date.",
        decision: "rejected",
      },
    ],
    versions: [
      {
        id: "RCSA-4005-V1",
        version: 1,
        editedBy: "Fatima Al-Zahra",
        editedAt: "2026-07-05",
        summary: "Initial self-assessment submitted",
      },
    ],
  },
  {
    id: "RCSA-4006",
    cycleId: "RCSA-2026-Q3",
    businessUnit: "Risk & Compliance",
    process: "AML Monitoring",
    subProcess: "Transaction Alert Disposition",
    owner: "Sara Al-Amin",
    assessor: "Priya Nair",
    status: "approved",
    overallInherentRisk: "high",
    overallResidualRisk: "low",
    actionRecommendations: [
      "Retrain alert-scoring model on the last 12 months of disposition data",
    ],
    submittedAt: "2026-07-08",
    approvedAt: "2026-07-16",
    approvedBy: "Layla Haddad",
    updatedAt: "2026-07-16",
    risks: [
      {
        id: "RCSA-4006-R1",
        description: "Suspicious activity alert closed without adequate investigation",
        category: "Compliance",
        inherentLikelihood: 3,
        inherentImpact: 4,
        inherentRisk: "high",
        residualLikelihood: 1,
        residualImpact: 3,
        residualRisk: "low",
        controls: [
          {
            id: "RCSA-4006-C1",
            name: "Quality assurance review of 10% of closed alerts monthly",
            type: "detective",
            effectiveness: "highly-effective",
          },
          {
            id: "RCSA-4006-C2",
            name: "Two-tier alert disposition (analyst + senior reviewer)",
            type: "preventive",
            effectiveness: "effective",
          },
        ],
        recommendation: "Maintain controls; refresh model to reduce false-positive volume.",
      },
    ],
    reviewHistory: [
      {
        id: "RCSA-4006-REV1",
        reviewer: "Layla Haddad",
        date: "2026-07-16",
        comment: "Strong control environment. Approved.",
        decision: "approved",
      },
    ],
    versions: [
      {
        id: "RCSA-4006-V1",
        version: 1,
        editedBy: "Sara Al-Amin",
        editedAt: "2026-07-08",
        summary: "Initial self-assessment submitted",
      },
    ],
  },
  {
    id: "RCSA-3011",
    cycleId: "RCSA-2026-Q2",
    businessUnit: "Human Resources",
    process: "Payroll Processing",
    subProcess: "Salary Change Authorization",
    owner: "Yusuf Karimi",
    assessor: "Priya Nair",
    status: "approved",
    overallInherentRisk: "medium",
    overallResidualRisk: "low",
    actionRecommendations: [],
    submittedAt: "2026-05-20",
    approvedAt: "2026-05-29",
    approvedBy: "Layla Haddad",
    updatedAt: "2026-05-29",
    risks: [
      {
        id: "RCSA-3011-R1",
        description: "Unauthorized salary change processed in payroll system",
        category: "Operational",
        inherentLikelihood: 2,
        inherentImpact: 3,
        inherentRisk: "medium",
        residualLikelihood: 1,
        residualImpact: 2,
        residualRisk: "low",
        controls: [
          {
            id: "RCSA-3011-C1",
            name: "HR Business Partner approval workflow for all salary changes",
            type: "preventive",
            effectiveness: "highly-effective",
          },
        ],
        recommendation: "No further action required.",
      },
    ],
    reviewHistory: [
      {
        id: "RCSA-3011-REV1",
        reviewer: "Layla Haddad",
        date: "2026-05-29",
        comment: "Approved without changes.",
        decision: "approved",
      },
    ],
    versions: [
      {
        id: "RCSA-3011-V1",
        version: 1,
        editedBy: "Yusuf Karimi",
        editedAt: "2026-05-20",
        summary: "Initial self-assessment submitted",
      },
    ],
  },
  {
    id: "RCSA-3012",
    cycleId: "RCSA-2026-Q2",
    businessUnit: "Finance",
    process: "Financial Close",
    subProcess: "Journal Entry Review",
    owner: "Ahmed Nasser",
    assessor: "Priya Nair",
    status: "approved",
    overallInherentRisk: "medium",
    overallResidualRisk: "low",
    actionRecommendations: [
      "Extend automated journal entry threshold rules to intercompany entries",
    ],
    submittedAt: "2026-05-15",
    approvedAt: "2026-05-25",
    approvedBy: "Layla Haddad",
    updatedAt: "2026-05-25",
    risks: [
      {
        id: "RCSA-3012-R1",
        description: "Material misstatement from unreviewed manual journal entry",
        category: "Financial",
        inherentLikelihood: 2,
        inherentImpact: 4,
        inherentRisk: "medium",
        residualLikelihood: 1,
        residualImpact: 3,
        residualRisk: "low",
        controls: [
          {
            id: "RCSA-3012-C1",
            name: "Segregation of duties between preparer and approver",
            type: "preventive",
            effectiveness: "effective",
          },
          {
            id: "RCSA-3012-C2",
            name: "Automated threshold flagging for entries above $50K",
            type: "detective",
            effectiveness: "effective",
          },
        ],
        recommendation: "Extend threshold rules to intercompany entries as noted.",
      },
    ],
    reviewHistory: [
      {
        id: "RCSA-3012-REV1",
        reviewer: "Layla Haddad",
        date: "2026-05-25",
        comment: "Approved. Track the intercompany extension as a follow-up action.",
        decision: "approved",
      },
    ],
    versions: [
      {
        id: "RCSA-3012-V1",
        version: 1,
        editedBy: "Ahmed Nasser",
        editedAt: "2026-05-15",
        summary: "Initial self-assessment submitted",
      },
    ],
  },
];
