import type { RiskItem } from "@/types";

export const risks: RiskItem[] = [
  {
    id: "RSK-1042",
    title: "Third-party vendor data breach exposure",
    category: "Cybersecurity",
    owner: "Layla Haddad",
    likelihood: 4,
    impact: 5,
    status: "mitigating",
    updatedAt: "2026-07-28",
  },
  {
    id: "RSK-1041",
    title: "Regulatory non-compliance in APAC markets",
    category: "Compliance",
    owner: "Marcus Chen",
    likelihood: 3,
    impact: 5,
    status: "open",
    updatedAt: "2026-07-26",
  },
  {
    id: "RSK-1038",
    title: "Key supplier concentration risk",
    category: "Operational",
    owner: "Sara Al-Amin",
    likelihood: 3,
    impact: 4,
    status: "open",
    updatedAt: "2026-07-25",
  },
  {
    id: "RSK-1035",
    title: "Foreign exchange volatility exposure",
    category: "Financial",
    owner: "Daniel Osei",
    likelihood: 4,
    impact: 3,
    status: "mitigating",
    updatedAt: "2026-07-22",
  },
  {
    id: "RSK-1030",
    title: "Legacy ERP system end-of-life",
    category: "Technology",
    owner: "Priya Nair",
    likelihood: 5,
    impact: 4,
    status: "open",
    updatedAt: "2026-07-20",
  },
  {
    id: "RSK-1027",
    title: "Talent attrition in engineering leadership",
    category: "Human Capital",
    owner: "Omar Farouk",
    likelihood: 3,
    impact: 3,
    status: "mitigating",
    updatedAt: "2026-07-18",
  },
  {
    id: "RSK-1022",
    title: "Data residency violation in cloud migration",
    category: "Compliance",
    owner: "Layla Haddad",
    likelihood: 2,
    impact: 5,
    status: "open",
    updatedAt: "2026-07-15",
  },
  {
    id: "RSK-1019",
    title: "Business continuity gap in payment processing",
    category: "Operational",
    owner: "Marcus Chen",
    likelihood: 2,
    impact: 4,
    status: "closed",
    updatedAt: "2026-07-10",
  },
  {
    id: "RSK-1015",
    title: "Insufficient insurance coverage for climate events",
    category: "Financial",
    owner: "Daniel Osei",
    likelihood: 2,
    impact: 3,
    status: "open",
    updatedAt: "2026-07-08",
  },
  {
    id: "RSK-1011",
    title: "Shadow IT proliferation across business units",
    category: "Technology",
    owner: "Priya Nair",
    likelihood: 3,
    impact: 2,
    status: "mitigating",
    updatedAt: "2026-07-04",
  },
  {
    id: "RSK-1008",
    title: "Anti-bribery and corruption control gaps",
    category: "Compliance",
    owner: "Sara Al-Amin",
    likelihood: 1,
    impact: 5,
    status: "open",
    updatedAt: "2026-06-30",
  },
  {
    id: "RSK-1004",
    title: "Customer concentration in top 3 accounts",
    category: "Strategic",
    owner: "Omar Farouk",
    likelihood: 2,
    impact: 2,
    status: "closed",
    updatedAt: "2026-06-24",
  },
];

export const riskCategoryBreakdown = [
  { label: "Cybersecurity", value: 18 },
  { label: "Compliance", value: 24 },
  { label: "Operational", value: 15 },
  { label: "Financial", value: 12 },
  { label: "Technology", value: 20 },
  { label: "Strategic", value: 8 },
];

export const riskTrend = [
  { label: "Feb", value: 58 },
  { label: "Mar", value: 62 },
  { label: "Apr", value: 55 },
  { label: "May", value: 67 },
  { label: "Jun", value: 71 },
  { label: "Jul", value: 64 },
];
