import type { RiskItem } from "@/types";

export const risks: RiskItem[] = [
  {
    id: "RSK-1042",
    title: "Third-party vendor data breach exposure",
    description:
      "Growing reliance on third-party SaaS and data-processing vendors increases exposure to a breach originating outside direct organizational control.",
    department: "Risk & Compliance",
    category: "Cybersecurity",
    subcategory: "Third-Party Access",
    riskSource: "Risk Assessment Workshop",
    riskType: "Technology",
    strategicObjective: "Ensure regulatory compliance",
    rootCause:
      "Vendor onboarding process lacks a mandatory security assessment prior to granting data access, allowing third parties with weak controls to integrate with core systems.",
    consequences:
      "Regulatory fines, customer data exposure, reputational damage, and potential contract termination with key enterprise clients.",
    existingControls:
      "Vendor security questionnaire completed annually; SOC 2 report requested for tier-1 vendors; contractual data protection clauses in place.",
    controlEffectiveness: "partially-effective",
    inherentLikelihood: 4,
    inherentImpact: 5,
    inherentRisk: "critical",
    likelihood: 3,
    impact: 4,
    targetLikelihood: 2,
    targetImpact: 3,
    targetRisk: "medium",
    riskTreatment: "mitigate",
    reviewFrequency: "quarterly",
    nextReviewDate: "2026-09-30",
    owner: "Layla Haddad",
    status: "mitigating",
    workflowStatus: "approved",
    workflowHistory: [
      {
        id: "WFT-RSK-1042-3",
        fromStatus: "under-review",
        toStatus: "approved",
        actor: "Layla Haddad",
        comment: "Remediation plan and residual scoring approved.",
        timestamp: "2026-07-15 11:00",
      },
      {
        id: "WFT-RSK-1042-2",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Marcus Chen",
        comment: "Submitting remediation plan for sign-off.",
        timestamp: "2026-06-05 09:30",
      },
      {
        id: "WFT-RSK-1042-1",
        fromStatus: "draft",
        toStatus: "draft",
        actor: "Layla Haddad",
        comment: "Risk logged in the register.",
        timestamp: "2026-05-02 08:30",
      },
    ],
    dueDate: "2026-09-15",
    isArchived: false,
    createdBy: "Layla Haddad",
    createdAt: "2026-05-02",
    updatedAt: "2026-07-28",
    attachments: [
      {
        id: "ATT-1",
        name: "Vendor Security Assessment - CloudSecure Inc.pdf",
        type: "pdf",
        size: "1.4 MB",
        uploadedBy: "Layla Haddad",
        uploadedAt: "2026-07-10",
      },
      {
        id: "ATT-2",
        name: "Third-Party Risk Remediation Plan.xlsx",
        type: "xls",
        size: "620 KB",
        uploadedBy: "Marcus Chen",
        uploadedAt: "2026-07-22",
      },
    ],
    comments: [
      {
        id: "CMT-1",
        author: "Marcus Chen",
        authorInitials: "MC",
        message:
          "Flagged this to Procurement — all new vendor contracts now require the SOC 2 clause before signature.",
        createdAt: "2026-07-18",
      },
      {
        id: "CMT-2",
        author: "Layla Haddad",
        authorInitials: "LH",
        message:
          "Remediation plan looks solid. Let's revisit residual scoring once the Q3 vendor re-assessment closes out.",
        createdAt: "2026-07-28",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-1",
        title: "Complete SOC 2 Type II review for all tier-1 vendors",
        owner: "Marcus Chen",
        dueDate: "2026-08-15",
        status: "in-progress",
        progress: 65,
      },
      {
        id: "TRT-2",
        title: "Deploy mandatory security questionnaire v2 for onboarding",
        owner: "Layla Haddad",
        dueDate: "2026-07-20",
        status: "not-started",
        progress: 0,
      },
    ],
    auditTrail: [
      {
        id: "AUD-1",
        timestamp: "2026-07-28 14:02",
        user: "Layla Haddad",
        action: "Added comment",
        details: "Commented on residual scoring timeline",
      },
      {
        id: "AUD-2",
        timestamp: "2026-07-22 09:40",
        user: "Marcus Chen",
        action: "Uploaded attachment",
        details: "Third-Party Risk Remediation Plan.xlsx",
      },
      {
        id: "AUD-3",
        timestamp: "2026-07-15 11:00",
        user: "Layla Haddad",
        action: "Workflow status changed",
        details: "Moved to Approved",
      },
      {
        id: "AUD-4",
        timestamp: "2026-07-10 16:20",
        user: "Layla Haddad",
        action: "Uploaded attachment",
        details: "Vendor Security Assessment - CloudSecure Inc.pdf",
      },
      {
        id: "AUD-5",
        timestamp: "2026-06-05 09:30",
        user: "Marcus Chen",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-6",
        timestamp: "2026-06-02 10:15",
        user: "Layla Haddad",
        action: "Updated risk status",
        details: "Status changed from Open to Mitigating",
      },
      {
        id: "AUD-7",
        timestamp: "2026-05-02 08:30",
        user: "Layla Haddad",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-1",
        version: 2,
        editedBy: "Layla Haddad",
        editedAt: "2026-06-02",
        summary: "Updated status to Mitigating and refreshed existing controls",
        snapshot: {
          title: "Third-party vendor data breach exposure",
          status: "mitigating",
          workflowStatus: "under-review",
          likelihood: 4,
          impact: 5,
          inherentRisk: "critical",
          targetRisk: "medium",
        },
      },
      {
        id: "VER-2",
        version: 1,
        editedBy: "Layla Haddad",
        editedAt: "2026-05-02",
        summary: "Risk created",
        snapshot: {
          title: "Third-party vendor data breach exposure",
          status: "open",
          workflowStatus: "draft",
          likelihood: 4,
          impact: 5,
          inherentRisk: "critical",
          targetRisk: "medium",
        },
      },
    ],
  },
  {
    id: "RSK-1041",
    title: "Regulatory non-compliance in APAC markets",
    description:
      "Rapid expansion into new APAC jurisdictions has outpaced formal regulatory mapping, creating potential licensing and filing gaps.",
    department: "Risk & Compliance",
    category: "Compliance",
    subcategory: "Cross-Border Regulation",
    riskSource: "External Consultant Review",
    riskType: "Compliance",
    strategicObjective: "Expand into new markets",
    rootCause:
      "Rapid market expansion outpaced local regulatory mapping, leaving gaps in licensing requirements across three APAC jurisdictions.",
    consequences:
      "Regulatory sanctions, forced suspension of local operations, and delays to planned market entry timelines.",
    existingControls:
      "Outside counsel engaged in Singapore and Hong Kong; quarterly regulatory horizon-scanning process introduced.",
    controlEffectiveness: "partially-effective",
    inherentLikelihood: 4,
    inherentImpact: 5,
    inherentRisk: "critical",
    likelihood: 3,
    impact: 5,
    targetLikelihood: 2,
    targetImpact: 3,
    targetRisk: "medium",
    riskTreatment: "mitigate",
    reviewFrequency: "monthly",
    nextReviewDate: "2026-08-10",
    owner: "Marcus Chen",
    status: "open",
    workflowStatus: "under-review",
    workflowHistory: [
      {
        id: "WFT-RSK-1041-1",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Marcus Chen",
        comment: "Submitting APAC regulatory gap analysis for review.",
        timestamp: "2026-07-05 10:00",
      },
    ],
    dueDate: "2026-08-20",
    isArchived: false,
    createdBy: "Marcus Chen",
    createdAt: "2026-04-11",
    updatedAt: "2026-07-26",
    attachments: [
      {
        id: "ATT-3",
        name: "APAC Regulatory Gap Analysis.pdf",
        type: "pdf",
        size: "2.1 MB",
        uploadedBy: "Marcus Chen",
        uploadedAt: "2026-06-20",
      },
    ],
    comments: [
      {
        id: "CMT-3",
        author: "Sara Al-Amin",
        authorInitials: "SA",
        message:
          "Internal audit can support with a licensing checklist for the Hong Kong entity if useful.",
        createdAt: "2026-07-05",
      },
      {
        id: "CMT-4",
        author: "Marcus Chen",
        authorInitials: "MC",
        message: "That would help — will loop you in next week.",
        createdAt: "2026-07-26",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-3",
        title: "Complete licensing gap remediation in Hong Kong",
        owner: "Marcus Chen",
        dueDate: "2026-08-20",
        status: "in-progress",
        progress: 40,
      },
      {
        id: "TRT-4",
        title: "Establish quarterly regulatory horizon-scanning cadence",
        owner: "Sara Al-Amin",
        dueDate: "2026-09-01",
        status: "not-started",
        progress: 0,
      },
    ],
    auditTrail: [
      {
        id: "AUD-8",
        timestamp: "2026-07-26 15:10",
        user: "Marcus Chen",
        action: "Added comment",
        details: "Replied to Sara Al-Amin",
      },
      {
        id: "AUD-9",
        timestamp: "2026-07-05 10:00",
        user: "Marcus Chen",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-10",
        timestamp: "2026-07-05 10:00",
        user: "Sara Al-Amin",
        action: "Added comment",
        details: "Offered audit support on licensing checklist",
      },
      {
        id: "AUD-11",
        timestamp: "2026-06-20 13:45",
        user: "Marcus Chen",
        action: "Uploaded attachment",
        details: "APAC Regulatory Gap Analysis.pdf",
      },
      {
        id: "AUD-12",
        timestamp: "2026-04-11 09:00",
        user: "Marcus Chen",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-3",
        version: 1,
        editedBy: "Marcus Chen",
        editedAt: "2026-04-11",
        summary: "Risk created",
        snapshot: {
          title: "Regulatory non-compliance in APAC markets",
          status: "open",
          workflowStatus: "draft",
          likelihood: 3,
          impact: 5,
          inherentRisk: "critical",
          targetRisk: "medium",
        },
      },
    ],
  },
  {
    id: "RSK-1038",
    title: "Key supplier concentration risk",
    description:
      "Reliance on a single component supplier for the majority of critical parts creates exposure to disruption from that vendor alone.",
    department: "Internal Audit",
    category: "Operational",
    subcategory: "Supply Chain",
    riskSource: "Internal Audit Finding",
    riskType: "Operational",
    strategicObjective: "Build a resilient supply chain",
    rootCause:
      "Single-source dependency on one component supplier representing 68% of critical parts procurement.",
    consequences:
      "Production line stoppages, missed customer delivery commitments, and premium-priced emergency sourcing costs.",
    existingControls:
      "Dual-sourcing initiative in progress; 90-day safety stock maintained at primary distribution center.",
    controlEffectiveness: "partially-effective",
    inherentLikelihood: 3,
    inherentImpact: 4,
    inherentRisk: "high",
    likelihood: 3,
    impact: 4,
    targetLikelihood: 2,
    targetImpact: 2,
    targetRisk: "low",
    riskTreatment: "mitigate",
    reviewFrequency: "quarterly",
    nextReviewDate: "2026-10-01",
    owner: "Sara Al-Amin",
    status: "open",
    workflowStatus: "draft",
    workflowHistory: [],
    dueDate: "2026-09-01",
    isArchived: false,
    createdBy: "Sara Al-Amin",
    createdAt: "2026-05-18",
    updatedAt: "2026-07-25",
    attachments: [
      {
        id: "ATT-4",
        name: "Supplier Concentration Analysis.xlsx",
        type: "xls",
        size: "780 KB",
        uploadedBy: "Sara Al-Amin",
        uploadedAt: "2026-06-01",
      },
      {
        id: "ATT-5",
        name: "Dual-Sourcing RFP Shortlist.doc",
        type: "doc",
        size: "410 KB",
        uploadedBy: "Omar Farouk",
        uploadedAt: "2026-07-12",
      },
    ],
    comments: [
      {
        id: "CMT-5",
        author: "Omar Farouk",
        authorInitials: "OF",
        message:
          "Shortlisted two alternate suppliers; qualification audits scheduled for August.",
        createdAt: "2026-07-25",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-5",
        title: "Qualify two alternate suppliers",
        owner: "Omar Farouk",
        dueDate: "2026-08-31",
        status: "in-progress",
        progress: 50,
      },
    ],
    auditTrail: [
      {
        id: "AUD-13",
        timestamp: "2026-07-25 09:20",
        user: "Omar Farouk",
        action: "Added comment",
        details: "Update on dual-sourcing progress",
      },
      {
        id: "AUD-14",
        timestamp: "2026-07-12 14:00",
        user: "Omar Farouk",
        action: "Uploaded attachment",
        details: "Dual-Sourcing RFP Shortlist.doc",
      },
      {
        id: "AUD-15",
        timestamp: "2026-06-01 11:30",
        user: "Sara Al-Amin",
        action: "Uploaded attachment",
        details: "Supplier Concentration Analysis.xlsx",
      },
      {
        id: "AUD-16",
        timestamp: "2026-05-18 08:00",
        user: "Sara Al-Amin",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-4",
        version: 1,
        editedBy: "Sara Al-Amin",
        editedAt: "2026-05-18",
        summary: "Risk created",
        snapshot: {
          title: "Key supplier concentration risk",
          status: "open",
          workflowStatus: "draft",
          likelihood: 3,
          impact: 4,
          inherentRisk: "high",
          targetRisk: "low",
        },
      },
    ],
  },
  {
    id: "RSK-1035",
    title: "Foreign exchange volatility exposure",
    description:
      "Unhedged receivables denominated in volatile emerging-market currencies expose reported earnings to sudden FX swings.",
    department: "Finance",
    category: "Financial",
    subcategory: "Foreign Exchange",
    riskSource: "Management Self-Identification",
    riskType: "Financial",
    strategicObjective: "Strengthen financial resilience",
    rootCause:
      "Unhedged receivables in emerging market currencies exposed to sudden depreciation.",
    consequences:
      "Reduced reported earnings, missed budget targets, and increased volatility in quarterly financial results.",
    existingControls:
      "50% of forecasted exposure hedged via forward contracts; monthly Treasury exposure review.",
    controlEffectiveness: "effective",
    inherentLikelihood: 4,
    inherentImpact: 3,
    inherentRisk: "high",
    likelihood: 3,
    impact: 3,
    targetLikelihood: 2,
    targetImpact: 2,
    targetRisk: "low",
    riskTreatment: "transfer",
    reviewFrequency: "monthly",
    nextReviewDate: "2026-08-05",
    owner: "Daniel Osei",
    status: "mitigating",
    workflowStatus: "approved",
    workflowHistory: [
      {
        id: "WFT-RSK-1035-2",
        fromStatus: "under-review",
        toStatus: "approved",
        actor: "Layla Haddad",
        comment: "Hedging strategy approved for continued execution.",
        timestamp: "2026-06-10 13:00",
      },
      {
        id: "WFT-RSK-1035-1",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Daniel Osei",
        comment: "Submitting Q2 hedging report for approval.",
        timestamp: "2026-05-20 09:00",
      },
    ],
    dueDate: "2026-08-30",
    isArchived: false,
    createdBy: "Daniel Osei",
    createdAt: "2026-04-25",
    updatedAt: "2026-07-22",
    attachments: [
      {
        id: "ATT-6",
        name: "FX Exposure Hedging Report - Q2.pdf",
        type: "pdf",
        size: "1.1 MB",
        uploadedBy: "Daniel Osei",
        uploadedAt: "2026-07-15",
      },
    ],
    comments: [
      {
        id: "CMT-6",
        author: "Daniel Osei",
        authorInitials: "DO",
        message:
          "Increasing hedge ratio to 65% for Q3 given continued volatility in the Naira and Rand.",
        createdAt: "2026-07-22",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-6",
        title: "Increase FX hedge ratio to 65% for Q3",
        owner: "Daniel Osei",
        dueDate: "2026-08-31",
        status: "in-progress",
        progress: 70,
      },
    ],
    auditTrail: [
      {
        id: "AUD-17",
        timestamp: "2026-07-22 10:05",
        user: "Daniel Osei",
        action: "Added comment",
        details: "Noted increase in Q3 hedge ratio",
      },
      {
        id: "AUD-18",
        timestamp: "2026-07-15 09:00",
        user: "Daniel Osei",
        action: "Uploaded attachment",
        details: "FX Exposure Hedging Report - Q2.pdf",
      },
      {
        id: "AUD-19",
        timestamp: "2026-06-10 13:00",
        user: "Layla Haddad",
        action: "Workflow status changed",
        details: "Moved to Approved",
      },
      {
        id: "AUD-20",
        timestamp: "2026-05-20 09:00",
        user: "Daniel Osei",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-21",
        timestamp: "2026-04-25 08:45",
        user: "Daniel Osei",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-5",
        version: 1,
        editedBy: "Daniel Osei",
        editedAt: "2026-04-25",
        summary: "Risk created",
        snapshot: {
          title: "Foreign exchange volatility exposure",
          status: "mitigating",
          workflowStatus: "draft",
          likelihood: 4,
          impact: 3,
          inherentRisk: "high",
          targetRisk: "low",
        },
      },
    ],
  },
  {
    id: "RSK-1030",
    title: "Legacy ERP system end-of-life",
    description:
      "The core ERP platform is approaching vendor end-of-support with no committed migration plan, threatening continuity of financial and operational processing.",
    department: "Technology",
    category: "Technology",
    subcategory: "Legacy Systems",
    riskSource: "Internal Audit Finding",
    riskType: "Technology",
    strategicObjective: "Drive digital transformation",
    rootCause:
      "Vendor has announced end of extended support in 14 months with no committed migration plan in place.",
    consequences:
      "Loss of vendor patches and security updates, unplanned system outages, and compliance exposure from unsupported software.",
    existingControls:
      "Compensating monitoring controls added around core modules; migration business case drafted for board review.",
    controlEffectiveness: "partially-effective",
    inherentLikelihood: 5,
    inherentImpact: 4,
    inherentRisk: "critical",
    likelihood: 5,
    impact: 4,
    targetLikelihood: 2,
    targetImpact: 3,
    targetRisk: "medium",
    riskTreatment: "mitigate",
    reviewFrequency: "monthly",
    nextReviewDate: "2026-08-08",
    owner: "Priya Nair",
    status: "open",
    workflowStatus: "under-review",
    workflowHistory: [
      {
        id: "WFT-RSK-1030-1",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Priya Nair",
        comment: "Business case submitted for Chief Risk Officer sign-off.",
        timestamp: "2026-07-01 11:00",
      },
    ],
    dueDate: "2026-10-15",
    isArchived: false,
    createdBy: "Priya Nair",
    createdAt: "2026-03-30",
    updatedAt: "2026-07-20",
    attachments: [
      {
        id: "ATT-7",
        name: "ERP Migration Business Case.pptx",
        type: "ppt",
        size: "3.4 MB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-07-05",
      },
      {
        id: "ATT-8",
        name: "Legacy System Risk Assessment.pdf",
        type: "pdf",
        size: "1.9 MB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-05-14",
      },
    ],
    comments: [
      {
        id: "CMT-7",
        author: "Priya Nair",
        authorInitials: "PN",
        message:
          "Business case submitted to the Technology Steering Committee for the September budget cycle.",
        createdAt: "2026-07-20",
      },
      {
        id: "CMT-8",
        author: "Layla Haddad",
        authorInitials: "LH",
        message:
          "This needs board visibility given the timeline pressure — adding to next risk committee agenda.",
        createdAt: "2026-07-21",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-7",
        title: "Secure board approval for ERP migration budget",
        owner: "Priya Nair",
        dueDate: "2026-09-01",
        status: "in-progress",
        progress: 30,
      },
      {
        id: "TRT-8",
        title: "Implement compensating monitoring controls",
        owner: "Priya Nair",
        dueDate: "2026-07-15",
        status: "completed",
        progress: 100,
      },
    ],
    auditTrail: [
      {
        id: "AUD-22",
        timestamp: "2026-07-21 16:00",
        user: "Layla Haddad",
        action: "Added comment",
        details: "Escalated to risk committee agenda",
      },
      {
        id: "AUD-23",
        timestamp: "2026-07-20 12:30",
        user: "Priya Nair",
        action: "Added comment",
        details: "Business case submitted to steering committee",
      },
      {
        id: "AUD-24",
        timestamp: "2026-07-05 09:15",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "ERP Migration Business Case.pptx",
      },
      {
        id: "AUD-25",
        timestamp: "2026-07-01 11:00",
        user: "Priya Nair",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-26",
        timestamp: "2026-05-14 10:20",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "Legacy System Risk Assessment.pdf",
      },
      {
        id: "AUD-27",
        timestamp: "2026-03-30 08:00",
        user: "Priya Nair",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-6",
        version: 2,
        editedBy: "Priya Nair",
        editedAt: "2026-05-14",
        summary:
          "Added detailed legacy system risk assessment and refreshed controls",
        snapshot: {
          title: "Legacy ERP system end-of-life",
          status: "open",
          workflowStatus: "draft",
          likelihood: 5,
          impact: 4,
          inherentRisk: "critical",
          targetRisk: "medium",
        },
      },
      {
        id: "VER-7",
        version: 1,
        editedBy: "Priya Nair",
        editedAt: "2026-03-30",
        summary: "Risk created",
        snapshot: {
          title: "Legacy ERP system end-of-life",
          status: "open",
          workflowStatus: "draft",
          likelihood: 5,
          impact: 4,
          inherentRisk: "critical",
          targetRisk: "medium",
        },
      },
    ],
  },
  {
    id: "RSK-1027",
    title: "Talent attrition in engineering leadership",
    description:
      "Below-market pay bands and a thin succession bench put senior engineering leadership continuity at risk.",
    department: "Operations",
    category: "Human Capital",
    subcategory: "Talent Attrition",
    riskSource: "Management Self-Identification",
    riskType: "Operational",
    strategicObjective: "Achieve operational excellence",
    rootCause:
      "Below-market compensation bands for senior engineering roles combined with limited succession bench strength.",
    consequences:
      "Loss of institutional knowledge, delayed product roadmaps, and increased recruitment and onboarding costs.",
    existingControls:
      "Retention bonuses issued to four key leaders; succession plan drafted for the VP Engineering role.",
    controlEffectiveness: "effective",
    inherentLikelihood: 3,
    inherentImpact: 3,
    inherentRisk: "medium",
    likelihood: 2,
    impact: 3,
    targetLikelihood: 1,
    targetImpact: 2,
    targetRisk: "low",
    riskTreatment: "mitigate",
    reviewFrequency: "semi-annual",
    nextReviewDate: "2026-11-01",
    owner: "Omar Farouk",
    status: "mitigating",
    workflowStatus: "approved",
    workflowHistory: [
      {
        id: "WFT-RSK-1027-2",
        fromStatus: "under-review",
        toStatus: "approved",
        actor: "Layla Haddad",
        comment: "Retention plan approved for rollout.",
        timestamp: "2026-06-01 10:00",
      },
      {
        id: "WFT-RSK-1027-1",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Omar Farouk",
        comment: "Submitting retention and succession plan.",
        timestamp: "2026-05-20 09:00",
      },
    ],
    dueDate: "2026-08-25",
    isArchived: false,
    createdBy: "Omar Farouk",
    createdAt: "2026-05-06",
    updatedAt: "2026-07-18",
    attachments: [
      {
        id: "ATT-9",
        name: "Engineering Compensation Benchmark.xlsx",
        type: "xls",
        size: "540 KB",
        uploadedBy: "Omar Farouk",
        uploadedAt: "2026-06-15",
      },
    ],
    comments: [
      {
        id: "CMT-9",
        author: "Omar Farouk",
        authorInitials: "OF",
        message:
          "HR has approved the revised banding; rollout begins next compensation cycle.",
        createdAt: "2026-07-18",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-9",
        title: "Roll out revised compensation bands",
        owner: "Omar Farouk",
        dueDate: "2026-08-15",
        status: "in-progress",
        progress: 80,
      },
    ],
    auditTrail: [
      {
        id: "AUD-28",
        timestamp: "2026-07-18 14:40",
        user: "Omar Farouk",
        action: "Added comment",
        details: "HR approved revised compensation banding",
      },
      {
        id: "AUD-29",
        timestamp: "2026-06-15 10:00",
        user: "Omar Farouk",
        action: "Uploaded attachment",
        details: "Engineering Compensation Benchmark.xlsx",
      },
      {
        id: "AUD-30",
        timestamp: "2026-06-01 10:00",
        user: "Layla Haddad",
        action: "Workflow status changed",
        details: "Moved to Approved",
      },
      {
        id: "AUD-31",
        timestamp: "2026-05-20 09:00",
        user: "Omar Farouk",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-32",
        timestamp: "2026-05-06 08:30",
        user: "Omar Farouk",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-8",
        version: 1,
        editedBy: "Omar Farouk",
        editedAt: "2026-05-06",
        summary: "Risk created",
        snapshot: {
          title: "Talent attrition in engineering leadership",
          status: "mitigating",
          workflowStatus: "draft",
          likelihood: 3,
          impact: 3,
          inherentRisk: "medium",
          targetRisk: "low",
        },
      },
    ],
  },
  {
    id: "RSK-1022",
    title: "Data residency violation in cloud migration",
    description:
      "The cloud migration program did not initially account for data residency obligations, risking non-compliant storage of regulated data.",
    department: "Risk & Compliance",
    category: "Compliance",
    subcategory: "Data Privacy",
    riskSource: "External Audit Finding",
    riskType: "Compliance",
    strategicObjective: "Ensure regulatory compliance",
    rootCause:
      "Cloud migration plan did not initially account for data residency requirements in the EU and KSA.",
    consequences:
      "Regulatory penalties under GDPR and local data protection law, and mandatory remediation of already-migrated workloads.",
    existingControls:
      "Region-locked storage buckets configured; data mapping exercise completed for EU workloads.",
    controlEffectiveness: "partially-effective",
    inherentLikelihood: 3,
    inherentImpact: 5,
    inherentRisk: "high",
    likelihood: 2,
    impact: 5,
    targetLikelihood: 1,
    targetImpact: 4,
    targetRisk: "low",
    riskTreatment: "mitigate",
    reviewFrequency: "quarterly",
    nextReviewDate: "2026-08-25",
    owner: "Layla Haddad",
    status: "open",
    workflowStatus: "draft",
    workflowHistory: [],
    dueDate: "2026-09-10",
    isArchived: false,
    createdBy: "Layla Haddad",
    createdAt: "2026-05-28",
    updatedAt: "2026-07-15",
    attachments: [
      {
        id: "ATT-10",
        name: "Data Residency Mapping - EU Workloads.pdf",
        type: "pdf",
        size: "980 KB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-07-02",
      },
    ],
    comments: [
      {
        id: "CMT-10",
        author: "Priya Nair",
        authorInitials: "PN",
        message:
          "KSA data mapping is next on the list — targeting completion by end of August.",
        createdAt: "2026-07-15",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-10",
        title: "Complete KSA data residency mapping",
        owner: "Priya Nair",
        dueDate: "2026-08-31",
        status: "in-progress",
        progress: 45,
      },
    ],
    auditTrail: [
      {
        id: "AUD-33",
        timestamp: "2026-07-15 11:20",
        user: "Priya Nair",
        action: "Added comment",
        details: "Update on KSA data mapping timeline",
      },
      {
        id: "AUD-34",
        timestamp: "2026-07-02 09:00",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "Data Residency Mapping - EU Workloads.pdf",
      },
      {
        id: "AUD-35",
        timestamp: "2026-05-28 08:00",
        user: "Layla Haddad",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-9",
        version: 1,
        editedBy: "Layla Haddad",
        editedAt: "2026-05-28",
        summary: "Risk created",
        snapshot: {
          title: "Data residency violation in cloud migration",
          status: "open",
          workflowStatus: "draft",
          likelihood: 2,
          impact: 5,
          inherentRisk: "high",
          targetRisk: "low",
        },
      },
    ],
  },
  {
    id: "RSK-1019",
    title: "Business continuity gap in payment processing",
    description:
      "The payment gateway was hosted from a single data center with no automated failover, risking prolonged outages of a revenue-critical system.",
    department: "Risk & Compliance",
    category: "Operational",
    subcategory: "Business Continuity",
    riskSource: "Internal Audit Finding",
    riskType: "Operational",
    strategicObjective: "Achieve operational excellence",
    rootCause:
      "Single data center hosted the payment gateway with no automated failover mechanism.",
    consequences:
      "Extended payment processing outages, lost transaction revenue, and breach of customer SLAs.",
    existingControls:
      "Secondary data center failover implemented and tested; recovery time objective reduced to 15 minutes.",
    controlEffectiveness: "highly-effective",
    inherentLikelihood: 3,
    inherentImpact: 4,
    inherentRisk: "high",
    likelihood: 1,
    impact: 2,
    targetLikelihood: 1,
    targetImpact: 2,
    targetRisk: "low",
    riskTreatment: "mitigate",
    reviewFrequency: "annual",
    nextReviewDate: "2027-07-01",
    owner: "Marcus Chen",
    status: "closed",
    workflowStatus: "closed",
    workflowHistory: [
      {
        id: "WFT-RSK-1019-3",
        fromStatus: "approved",
        toStatus: "closed",
        actor: "Layla Haddad",
        comment: "Closure approved based on successful failover testing.",
        timestamp: "2026-07-10 15:00",
      },
      {
        id: "WFT-RSK-1019-2",
        fromStatus: "under-review",
        toStatus: "approved",
        actor: "Priya Nair",
        comment: "Failover implementation verified.",
        timestamp: "2026-07-02 14:00",
      },
      {
        id: "WFT-RSK-1019-1",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Marcus Chen",
        comment: "Submitting failover test results for review.",
        timestamp: "2026-06-28 17:00",
      },
    ],
    dueDate: "2026-07-01",
    isArchived: false,
    createdBy: "Marcus Chen",
    createdAt: "2026-02-14",
    updatedAt: "2026-07-10",
    attachments: [
      {
        id: "ATT-11",
        name: "Failover Test Results - June 2026.pdf",
        type: "pdf",
        size: "1.2 MB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-06-28",
      },
      {
        id: "ATT-12",
        name: "BCP Closure Memo.doc",
        type: "doc",
        size: "310 KB",
        uploadedBy: "Marcus Chen",
        uploadedAt: "2026-07-10",
      },
    ],
    comments: [
      {
        id: "CMT-11",
        author: "Priya Nair",
        authorInitials: "PN",
        message:
          "Failover test completed successfully — RTO of 12 minutes achieved, within target.",
        createdAt: "2026-06-28",
      },
      {
        id: "CMT-12",
        author: "Marcus Chen",
        authorInitials: "MC",
        message: "Closing this out. Great work from the infrastructure team.",
        createdAt: "2026-07-10",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-11",
        title: "Implement secondary data-center failover",
        owner: "Priya Nair",
        dueDate: "2026-06-30",
        status: "completed",
        progress: 100,
      },
    ],
    auditTrail: [
      {
        id: "AUD-36",
        timestamp: "2026-07-10 15:00",
        user: "Layla Haddad",
        action: "Workflow status changed",
        details: "Moved to Closed",
      },
      {
        id: "AUD-37",
        timestamp: "2026-07-10 09:30",
        user: "Marcus Chen",
        action: "Updated risk status",
        details: "Status changed from Mitigating to Closed",
      },
      {
        id: "AUD-38",
        timestamp: "2026-07-02 14:00",
        user: "Priya Nair",
        action: "Workflow status changed",
        details: "Moved to Approved",
      },
      {
        id: "AUD-39",
        timestamp: "2026-06-28 17:00",
        user: "Marcus Chen",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-40",
        timestamp: "2026-06-28 16:45",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "Failover Test Results - June 2026.pdf",
      },
      {
        id: "AUD-41",
        timestamp: "2026-02-14 08:00",
        user: "Marcus Chen",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-10",
        version: 2,
        editedBy: "Marcus Chen",
        editedAt: "2026-07-10",
        summary: "Closed following successful failover testing",
        snapshot: {
          title: "Business continuity gap in payment processing",
          status: "closed",
          workflowStatus: "closed",
          likelihood: 1,
          impact: 2,
          inherentRisk: "high",
          targetRisk: "low",
        },
      },
      {
        id: "VER-11",
        version: 1,
        editedBy: "Marcus Chen",
        editedAt: "2026-02-14",
        summary: "Risk created",
        snapshot: {
          title: "Business continuity gap in payment processing",
          status: "open",
          workflowStatus: "draft",
          likelihood: 3,
          impact: 4,
          inherentRisk: "high",
          targetRisk: "low",
        },
      },
    ],
  },
  {
    id: "RSK-1015",
    title: "Insufficient insurance coverage for climate events",
    description:
      "Property insurance policy limits have not kept pace with asset growth or the rising frequency of climate-related events.",
    department: "Finance",
    category: "Financial",
    subcategory: "Insurance Coverage",
    riskSource: "Management Self-Identification",
    riskType: "Financial",
    strategicObjective: "Strengthen financial resilience",
    rootCause:
      "Property insurance policy limits have not been reassessed since 2019 despite asset base growth and increased climate event frequency.",
    consequences:
      "Underinsured losses following a major climate event, and unbudgeted capital outlay to cover the shortfall.",
    existingControls:
      "Insurance broker engaged for full policy review; interim coverage increase secured for the flagship facility.",
    controlEffectiveness: "partially-effective",
    inherentLikelihood: 2,
    inherentImpact: 3,
    inherentRisk: "medium",
    likelihood: 2,
    impact: 3,
    targetLikelihood: 1,
    targetImpact: 2,
    targetRisk: "low",
    riskTreatment: "mitigate",
    reviewFrequency: "annual",
    nextReviewDate: "2026-12-01",
    owner: "Daniel Osei",
    status: "open",
    workflowStatus: "draft",
    workflowHistory: [],
    dueDate: "2026-09-20",
    isArchived: false,
    createdBy: "Daniel Osei",
    createdAt: "2026-06-01",
    updatedAt: "2026-07-08",
    attachments: [
      {
        id: "ATT-13",
        name: "Insurance Policy Review - Draft.pdf",
        type: "pdf",
        size: "860 KB",
        uploadedBy: "Daniel Osei",
        uploadedAt: "2026-07-08",
      },
    ],
    comments: [],
    treatmentPlans: [
      {
        id: "TRT-12",
        title: "Complete full insurance policy review with broker",
        owner: "Daniel Osei",
        dueDate: "2026-09-15",
        status: "in-progress",
        progress: 25,
      },
    ],
    auditTrail: [
      {
        id: "AUD-42",
        timestamp: "2026-07-08 10:00",
        user: "Daniel Osei",
        action: "Uploaded attachment",
        details: "Insurance Policy Review - Draft.pdf",
      },
      {
        id: "AUD-43",
        timestamp: "2026-06-01 08:00",
        user: "Daniel Osei",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-12",
        version: 1,
        editedBy: "Daniel Osei",
        editedAt: "2026-06-01",
        summary: "Risk created",
        snapshot: {
          title: "Insufficient insurance coverage for climate events",
          status: "open",
          workflowStatus: "draft",
          likelihood: 2,
          impact: 3,
          inherentRisk: "medium",
          targetRisk: "low",
        },
      },
    ],
  },
  {
    id: "RSK-1011",
    title: "Shadow IT proliferation across business units",
    description:
      "Business units are procuring SaaS tools directly, bypassing IT security review and creating unmanaged data and access risk.",
    department: "Technology",
    category: "Technology",
    subcategory: "Shadow IT",
    riskSource: "Internal Audit Finding",
    riskType: "Technology",
    strategicObjective: "Drive digital transformation",
    rootCause:
      "Business units procure SaaS tools directly without IT security review due to a slow central procurement process.",
    consequences:
      "Unmanaged data exposure, licensing non-compliance, and duplicated spend across shadow tools.",
    existingControls:
      "SaaS discovery tool deployed across the network; expedited security review lane introduced for low-risk tools.",
    controlEffectiveness: "effective",
    inherentLikelihood: 3,
    inherentImpact: 2,
    inherentRisk: "medium",
    likelihood: 2,
    impact: 2,
    targetLikelihood: 1,
    targetImpact: 1,
    targetRisk: "low",
    riskTreatment: "mitigate",
    reviewFrequency: "quarterly",
    nextReviewDate: "2026-08-12",
    owner: "Priya Nair",
    status: "mitigating",
    workflowStatus: "rejected",
    workflowHistory: [
      {
        id: "WFT-RSK-1011-2",
        fromStatus: "under-review",
        toStatus: "rejected",
        actor: "Layla Haddad",
        comment:
          "Closure request rejected — need confirmation of full SaaS remediation across all business units before sign-off.",
        timestamp: "2026-07-04 09:30",
      },
      {
        id: "WFT-RSK-1011-1",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Priya Nair",
        comment: "Submitting for closure review.",
        timestamp: "2026-06-15 09:00",
      },
    ],
    dueDate: "2026-08-18",
    isArchived: false,
    createdBy: "Priya Nair",
    createdAt: "2026-04-30",
    updatedAt: "2026-07-04",
    attachments: [
      {
        id: "ATT-14",
        name: "Shadow IT Discovery Report.xlsx",
        type: "xls",
        size: "690 KB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-06-10",
      },
    ],
    comments: [
      {
        id: "CMT-13",
        author: "Priya Nair",
        authorInitials: "PN",
        message:
          "47 unsanctioned SaaS tools identified; 12 already brought into the approved catalog.",
        createdAt: "2026-07-04",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-13",
        title: "Bring remaining unsanctioned SaaS tools into approved catalog",
        owner: "Priya Nair",
        dueDate: "2026-08-10",
        status: "in-progress",
        progress: 70,
      },
    ],
    auditTrail: [
      {
        id: "AUD-44",
        timestamp: "2026-07-04 09:30",
        user: "Layla Haddad",
        action: "Workflow status changed",
        details: "Moved to Rejected",
      },
      {
        id: "AUD-45",
        timestamp: "2026-07-04 09:00",
        user: "Priya Nair",
        action: "Added comment",
        details: "Update on SaaS discovery remediation",
      },
      {
        id: "AUD-46",
        timestamp: "2026-06-15 09:00",
        user: "Priya Nair",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-47",
        timestamp: "2026-06-10 13:30",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "Shadow IT Discovery Report.xlsx",
      },
      {
        id: "AUD-48",
        timestamp: "2026-04-30 08:00",
        user: "Priya Nair",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-13",
        version: 1,
        editedBy: "Priya Nair",
        editedAt: "2026-04-30",
        summary: "Risk created",
        snapshot: {
          title: "Shadow IT proliferation across business units",
          status: "mitigating",
          workflowStatus: "draft",
          likelihood: 3,
          impact: 2,
          inherentRisk: "medium",
          targetRisk: "low",
        },
      },
    ],
  },
  {
    id: "RSK-1008",
    title: "Anti-bribery and corruption control gaps",
    description:
      "Inconsistent maintenance of gift and hospitality registers across regional offices weakens the anti-bribery control environment.",
    department: "Internal Audit",
    category: "Compliance",
    subcategory: "Anti-Bribery & Corruption",
    riskSource: "External Audit Finding",
    riskType: "Compliance",
    strategicObjective: "Protect brand reputation",
    rootCause:
      "Gift and hospitality register not consistently maintained across regional offices.",
    consequences:
      "Regulatory investigation, criminal or civil liability under anti-bribery law, and reputational damage with investors.",
    existingControls:
      "Mandatory annual anti-bribery training; gift register digitized and centrally monitored.",
    controlEffectiveness: "effective",
    inherentLikelihood: 3,
    inherentImpact: 5,
    inherentRisk: "high",
    likelihood: 1,
    impact: 5,
    targetLikelihood: 1,
    targetImpact: 4,
    targetRisk: "low",
    riskTreatment: "mitigate",
    reviewFrequency: "semi-annual",
    nextReviewDate: "2026-09-20",
    owner: "Sara Al-Amin",
    status: "open",
    workflowStatus: "under-review",
    workflowHistory: [
      {
        id: "WFT-RSK-1008-1",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Sara Al-Amin",
        comment: "Submitting regional rollout confirmation for review.",
        timestamp: "2026-06-30 10:30",
      },
    ],
    dueDate: "2026-09-05",
    isArchived: false,
    createdBy: "Sara Al-Amin",
    createdAt: "2026-05-20",
    updatedAt: "2026-06-30",
    attachments: [],
    comments: [
      {
        id: "CMT-14",
        author: "Sara Al-Amin",
        authorInitials: "SA",
        message:
          "Regional compliance leads confirmed rollout of the digital gift register in all offices by August.",
        createdAt: "2026-06-30",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-14",
        title: "Complete regional rollout of digital gift register",
        owner: "Sara Al-Amin",
        dueDate: "2026-08-31",
        status: "in-progress",
        progress: 85,
      },
    ],
    auditTrail: [
      {
        id: "AUD-49",
        timestamp: "2026-06-30 10:30",
        user: "Sara Al-Amin",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-50",
        timestamp: "2026-06-30 10:00",
        user: "Sara Al-Amin",
        action: "Added comment",
        details: "Confirmed regional rollout timeline",
      },
      {
        id: "AUD-51",
        timestamp: "2026-05-20 08:00",
        user: "Sara Al-Amin",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-14",
        version: 1,
        editedBy: "Sara Al-Amin",
        editedAt: "2026-05-20",
        summary: "Risk created",
        snapshot: {
          title: "Anti-bribery and corruption control gaps",
          status: "open",
          workflowStatus: "draft",
          likelihood: 1,
          impact: 5,
          inherentRisk: "high",
          targetRisk: "low",
        },
      },
    ],
  },
  {
    id: "RSK-1004",
    title: "Customer concentration in top 3 accounts",
    description:
      "The top three customer accounts represent a disproportionate share of annual revenue, exposing the business to concentration risk.",
    department: "Operations",
    category: "Strategic",
    subcategory: "Customer Concentration",
    riskSource: "Risk Assessment Workshop",
    riskType: "Strategic",
    strategicObjective: "Expand into new markets",
    rootCause:
      "Top 3 customers represent 46% of annual revenue following two years of organic growth concentration.",
    consequences:
      "Material revenue loss and equity valuation impact if any one of the top three accounts is lost or renegotiates terms.",
    existingControls:
      "New business development team scaled; diversification target set at board level; concentration reduced to 38%.",
    controlEffectiveness: "highly-effective",
    inherentLikelihood: 3,
    inherentImpact: 3,
    inherentRisk: "medium",
    likelihood: 2,
    impact: 2,
    targetLikelihood: 2,
    targetImpact: 2,
    targetRisk: "low",
    riskTreatment: "mitigate",
    reviewFrequency: "annual",
    nextReviewDate: "2027-01-20",
    owner: "Omar Farouk",
    status: "closed",
    workflowStatus: "closed",
    workflowHistory: [
      {
        id: "WFT-RSK-1004-3",
        fromStatus: "approved",
        toStatus: "closed",
        actor: "Layla Haddad",
        comment: "Concentration now within board-approved tolerance.",
        timestamp: "2026-06-24 11:00",
      },
      {
        id: "WFT-RSK-1004-2",
        fromStatus: "under-review",
        toStatus: "approved",
        actor: "Sara Al-Amin",
        comment: "Diversification progress verified against target.",
        timestamp: "2026-06-22 09:00",
      },
      {
        id: "WFT-RSK-1004-1",
        fromStatus: "draft",
        toStatus: "under-review",
        actor: "Omar Farouk",
        comment: "Submitting diversification progress report for closure.",
        timestamp: "2026-06-20 14:15",
      },
    ],
    dueDate: "2026-06-15",
    isArchived: true,
    createdBy: "Omar Farouk",
    createdAt: "2026-01-20",
    updatedAt: "2026-06-24",
    attachments: [
      {
        id: "ATT-15",
        name: "Revenue Diversification Progress Report.pdf",
        type: "pdf",
        size: "1.0 MB",
        uploadedBy: "Omar Farouk",
        uploadedAt: "2026-06-20",
      },
    ],
    comments: [
      {
        id: "CMT-15",
        author: "Omar Farouk",
        authorInitials: "OF",
        message:
          "Concentration down to 38% from 46% at start of year — closing as within board-approved tolerance.",
        createdAt: "2026-06-24",
      },
    ],
    treatmentPlans: [
      {
        id: "TRT-15",
        title: "Scale new business development team",
        owner: "Omar Farouk",
        dueDate: "2026-05-31",
        status: "completed",
        progress: 100,
      },
    ],
    auditTrail: [
      {
        id: "AUD-52",
        timestamp: "2026-06-24 11:00",
        user: "Layla Haddad",
        action: "Workflow status changed",
        details: "Moved to Closed",
      },
      {
        id: "AUD-53",
        timestamp: "2026-06-24 10:00",
        user: "Omar Farouk",
        action: "Updated risk status",
        details: "Status changed from Mitigating to Closed",
      },
      {
        id: "AUD-54",
        timestamp: "2026-06-22 09:00",
        user: "Sara Al-Amin",
        action: "Workflow status changed",
        details: "Moved to Approved",
      },
      {
        id: "AUD-55",
        timestamp: "2026-06-20 14:15",
        user: "Omar Farouk",
        action: "Workflow status changed",
        details: "Moved to Under Review",
      },
      {
        id: "AUD-56",
        timestamp: "2026-06-20 14:15",
        user: "Omar Farouk",
        action: "Uploaded attachment",
        details: "Revenue Diversification Progress Report.pdf",
      },
      {
        id: "AUD-57",
        timestamp: "2026-01-20 08:00",
        user: "Omar Farouk",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-15",
        version: 2,
        editedBy: "Omar Farouk",
        editedAt: "2026-06-24",
        summary: "Closed after concentration reduced to within tolerance",
        snapshot: {
          title: "Customer concentration in top 3 accounts",
          status: "closed",
          workflowStatus: "closed",
          likelihood: 2,
          impact: 2,
          inherentRisk: "medium",
          targetRisk: "low",
        },
      },
      {
        id: "VER-16",
        version: 1,
        editedBy: "Omar Farouk",
        editedAt: "2026-01-20",
        summary: "Risk created",
        snapshot: {
          title: "Customer concentration in top 3 accounts",
          status: "open",
          workflowStatus: "draft",
          likelihood: 3,
          impact: 3,
          inherentRisk: "medium",
          targetRisk: "low",
        },
      },
    ],
  },
];

export const riskCategoryBreakdown = [
  { label: "Cybersecurity", value: 18 },
  { label: "Compliance", value: 24 },
  { label: "Operational", value: 15 },
  { label: "Financial", value: 12 },
  { label: "Technology", value: 20 },
  { label: "Strategic", value: 8 },
];

export const riskTrend = [
  { label: "Feb", value: 58 },
  { label: "Mar", value: 62 },
  { label: "Apr", value: 55 },
  { label: "May", value: 67 },
  { label: "Jun", value: 71 },
  { label: "Jul", value: 64 },
];

export const riskTrendQuarterly = [
  { label: "Q3 2025", value: 59 },
  { label: "Q4 2025", value: 65 },
  { label: "Q1 2026", value: 70 },
  { label: "Q2 2026", value: 64 },
];

export const riskTrendYearly = [
  { label: "2023", value: 47 },
  { label: "2024", value: 55 },
  { label: "2025", value: 62 },
  { label: "2026", value: 68 },
];
