import type { RiskItem } from "@/types";

export const risks: RiskItem[] = [
  {
    id: "RSK-1042",
    title: "Third-party vendor data breach exposure",
    department: "Risk & Compliance",
    category: "Cybersecurity",
    subcategory: "Third-Party Access",
    rootCause:
      "Vendor onboarding process lacks a mandatory security assessment prior to granting data access, allowing third parties with weak controls to integrate with core systems.",
    existingControls:
      "Vendor security questionnaire completed annually; SOC 2 report requested for tier-1 vendors; contractual data protection clauses in place.",
    inherentRisk: "critical",
    owner: "Layla Haddad",
    likelihood: 4,
    impact: 5,
    status: "mitigating",
    dueDate: "2026-09-15",
    createdBy: "Layla Haddad",
    createdAt: "2026-05-02",
    updatedAt: "2026-07-28",
    attachments: [
      {
        id: "ATT-1",
        name: "Vendor Security Assessment - CloudSecure Inc.pdf",
        type: "pdf",
        size: "1.4 MB",
        uploadedBy: "Layla Haddad",
        uploadedAt: "2026-07-10",
      },
      {
        id: "ATT-2",
        name: "Third-Party Risk Remediation Plan.xlsx",
        type: "xls",
        size: "620 KB",
        uploadedBy: "Marcus Chen",
        uploadedAt: "2026-07-22",
      },
    ],
    comments: [
      {
        id: "CMT-1",
        author: "Marcus Chen",
        authorInitials: "MC",
        message:
          "Flagged this to Procurement — all new vendor contracts now require the SOC 2 clause before signature.",
        createdAt: "2026-07-18",
      },
      {
        id: "CMT-2",
        author: "Layla Haddad",
        authorInitials: "LH",
        message:
          "Remediation plan looks solid. Let's revisit residual scoring once the Q3 vendor re-assessment closes out.",
        createdAt: "2026-07-28",
      },
    ],
    approvals: [
      {
        id: "APR-STEP-1",
        role: "Department Head Approval",
        approver: "Marcus Chen",
        status: "approved",
        date: "2026-07-15",
        comment: "Remediation plan endorsed for Risk & Compliance.",
      },
      {
        id: "APR-STEP-2",
        role: "Chief Risk Officer Sign-off",
        approver: "Layla Haddad",
        status: "pending",
      },
    ],
    auditTrail: [
      {
        id: "AUD-1",
        timestamp: "2026-07-28 14:02",
        user: "Layla Haddad",
        action: "Added comment",
        details: "Commented on residual scoring timeline",
      },
      {
        id: "AUD-2",
        timestamp: "2026-07-22 09:40",
        user: "Marcus Chen",
        action: "Uploaded attachment",
        details: "Third-Party Risk Remediation Plan.xlsx",
      },
      {
        id: "AUD-3",
        timestamp: "2026-07-15 11:00",
        user: "Marcus Chen",
        action: "Approved workflow step",
        details: "Department Head Approval",
      },
      {
        id: "AUD-4",
        timestamp: "2026-07-10 16:20",
        user: "Layla Haddad",
        action: "Uploaded attachment",
        details: "Vendor Security Assessment - CloudSecure Inc.pdf",
      },
      {
        id: "AUD-5",
        timestamp: "2026-06-02 10:15",
        user: "Layla Haddad",
        action: "Updated risk status",
        details: "Status changed from Open to Mitigating",
      },
      {
        id: "AUD-6",
        timestamp: "2026-05-02 08:30",
        user: "Layla Haddad",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-1",
        version: 2,
        editedBy: "Layla Haddad",
        editedAt: "2026-06-02",
        summary: "Updated status to Mitigating and refreshed existing controls",
        snapshot: {
          title: "Third-party vendor data breach exposure",
          status: "mitigating",
          likelihood: 4,
          impact: 5,
          inherentRisk: "critical",
        },
      },
      {
        id: "VER-2",
        version: 1,
        editedBy: "Layla Haddad",
        editedAt: "2026-05-02",
        summary: "Risk created",
        snapshot: {
          title: "Third-party vendor data breach exposure",
          status: "open",
          likelihood: 4,
          impact: 5,
          inherentRisk: "critical",
        },
      },
    ],
  },
  {
    id: "RSK-1041",
    title: "Regulatory non-compliance in APAC markets",
    department: "Risk & Compliance",
    category: "Compliance",
    subcategory: "Cross-Border Regulation",
    rootCause:
      "Rapid market expansion outpaced local regulatory mapping, leaving gaps in licensing requirements across three APAC jurisdictions.",
    existingControls:
      "Outside counsel engaged in Singapore and Hong Kong; quarterly regulatory horizon-scanning process introduced.",
    inherentRisk: "critical",
    owner: "Marcus Chen",
    likelihood: 3,
    impact: 5,
    status: "open",
    dueDate: "2026-08-20",
    createdBy: "Marcus Chen",
    createdAt: "2026-04-11",
    updatedAt: "2026-07-26",
    attachments: [
      {
        id: "ATT-3",
        name: "APAC Regulatory Gap Analysis.pdf",
        type: "pdf",
        size: "2.1 MB",
        uploadedBy: "Marcus Chen",
        uploadedAt: "2026-06-20",
      },
    ],
    comments: [
      {
        id: "CMT-3",
        author: "Sara Al-Amin",
        authorInitials: "SA",
        message:
          "Internal audit can support with a licensing checklist for the Hong Kong entity if useful.",
        createdAt: "2026-07-05",
      },
      {
        id: "CMT-4",
        author: "Marcus Chen",
        authorInitials: "MC",
        message: "That would help — will loop you in next week.",
        createdAt: "2026-07-26",
      },
    ],
    approvals: [],
    auditTrail: [
      {
        id: "AUD-7",
        timestamp: "2026-07-26 15:10",
        user: "Marcus Chen",
        action: "Added comment",
        details: "Replied to Sara Al-Amin",
      },
      {
        id: "AUD-8",
        timestamp: "2026-07-05 10:00",
        user: "Sara Al-Amin",
        action: "Added comment",
        details: "Offered audit support on licensing checklist",
      },
      {
        id: "AUD-9",
        timestamp: "2026-06-20 13:45",
        user: "Marcus Chen",
        action: "Uploaded attachment",
        details: "APAC Regulatory Gap Analysis.pdf",
      },
      {
        id: "AUD-10",
        timestamp: "2026-04-11 09:00",
        user: "Marcus Chen",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-3",
        version: 1,
        editedBy: "Marcus Chen",
        editedAt: "2026-04-11",
        summary: "Risk created",
        snapshot: {
          title: "Regulatory non-compliance in APAC markets",
          status: "open",
          likelihood: 3,
          impact: 5,
          inherentRisk: "critical",
        },
      },
    ],
  },
  {
    id: "RSK-1038",
    title: "Key supplier concentration risk",
    department: "Internal Audit",
    category: "Operational",
    subcategory: "Supply Chain",
    rootCause:
      "Single-source dependency on one component supplier representing 68% of critical parts procurement.",
    existingControls:
      "Dual-sourcing initiative in progress; 90-day safety stock maintained at primary distribution center.",
    inherentRisk: "high",
    owner: "Sara Al-Amin",
    likelihood: 3,
    impact: 4,
    status: "open",
    dueDate: "2026-09-01",
    createdBy: "Sara Al-Amin",
    createdAt: "2026-05-18",
    updatedAt: "2026-07-25",
    attachments: [
      {
        id: "ATT-4",
        name: "Supplier Concentration Analysis.xlsx",
        type: "xls",
        size: "780 KB",
        uploadedBy: "Sara Al-Amin",
        uploadedAt: "2026-06-01",
      },
      {
        id: "ATT-5",
        name: "Dual-Sourcing RFP Shortlist.doc",
        type: "doc",
        size: "410 KB",
        uploadedBy: "Omar Farouk",
        uploadedAt: "2026-07-12",
      },
    ],
    comments: [
      {
        id: "CMT-5",
        author: "Omar Farouk",
        authorInitials: "OF",
        message:
          "Shortlisted two alternate suppliers; qualification audits scheduled for August.",
        createdAt: "2026-07-25",
      },
    ],
    approvals: [],
    auditTrail: [
      {
        id: "AUD-11",
        timestamp: "2026-07-25 09:20",
        user: "Omar Farouk",
        action: "Added comment",
        details: "Update on dual-sourcing progress",
      },
      {
        id: "AUD-12",
        timestamp: "2026-07-12 14:00",
        user: "Omar Farouk",
        action: "Uploaded attachment",
        details: "Dual-Sourcing RFP Shortlist.doc",
      },
      {
        id: "AUD-13",
        timestamp: "2026-06-01 11:30",
        user: "Sara Al-Amin",
        action: "Uploaded attachment",
        details: "Supplier Concentration Analysis.xlsx",
      },
      {
        id: "AUD-14",
        timestamp: "2026-05-18 08:00",
        user: "Sara Al-Amin",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-4",
        version: 1,
        editedBy: "Sara Al-Amin",
        editedAt: "2026-05-18",
        summary: "Risk created",
        snapshot: {
          title: "Key supplier concentration risk",
          status: "open",
          likelihood: 3,
          impact: 4,
          inherentRisk: "high",
        },
      },
    ],
  },
  {
    id: "RSK-1035",
    title: "Foreign exchange volatility exposure",
    department: "Finance",
    category: "Financial",
    subcategory: "Foreign Exchange",
    rootCause:
      "Unhedged receivables in emerging market currencies exposed to sudden depreciation.",
    existingControls:
      "50% of forecasted exposure hedged via forward contracts; monthly Treasury exposure review.",
    inherentRisk: "high",
    owner: "Daniel Osei",
    likelihood: 4,
    impact: 3,
    status: "mitigating",
    dueDate: "2026-08-30",
    createdBy: "Daniel Osei",
    createdAt: "2026-04-25",
    updatedAt: "2026-07-22",
    attachments: [
      {
        id: "ATT-6",
        name: "FX Exposure Hedging Report - Q2.pdf",
        type: "pdf",
        size: "1.1 MB",
        uploadedBy: "Daniel Osei",
        uploadedAt: "2026-07-15",
      },
    ],
    comments: [
      {
        id: "CMT-6",
        author: "Daniel Osei",
        authorInitials: "DO",
        message:
          "Increasing hedge ratio to 65% for Q3 given continued volatility in the Naira and Rand.",
        createdAt: "2026-07-22",
      },
    ],
    approvals: [
      {
        id: "APR-STEP-3",
        role: "Department Head Approval",
        approver: "Layla Haddad",
        status: "approved",
        date: "2026-06-10",
        comment: "Hedging strategy approved for continued execution.",
      },
    ],
    auditTrail: [
      {
        id: "AUD-15",
        timestamp: "2026-07-22 10:05",
        user: "Daniel Osei",
        action: "Added comment",
        details: "Noted increase in Q3 hedge ratio",
      },
      {
        id: "AUD-16",
        timestamp: "2026-07-15 09:00",
        user: "Daniel Osei",
        action: "Uploaded attachment",
        details: "FX Exposure Hedging Report - Q2.pdf",
      },
      {
        id: "AUD-17",
        timestamp: "2026-06-10 13:00",
        user: "Layla Haddad",
        action: "Approved workflow step",
        details: "Department Head Approval",
      },
      {
        id: "AUD-18",
        timestamp: "2026-04-25 08:45",
        user: "Daniel Osei",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-5",
        version: 1,
        editedBy: "Daniel Osei",
        editedAt: "2026-04-25",
        summary: "Risk created",
        snapshot: {
          title: "Foreign exchange volatility exposure",
          status: "mitigating",
          likelihood: 4,
          impact: 3,
          inherentRisk: "high",
        },
      },
    ],
  },
  {
    id: "RSK-1030",
    title: "Legacy ERP system end-of-life",
    department: "Technology",
    category: "Technology",
    subcategory: "Legacy Systems",
    rootCause:
      "Vendor has announced end of extended support in 14 months with no committed migration plan in place.",
    existingControls:
      "Compensating monitoring controls added around core modules; migration business case drafted for board review.",
    inherentRisk: "critical",
    owner: "Priya Nair",
    likelihood: 5,
    impact: 4,
    status: "open",
    dueDate: "2026-10-15",
    createdBy: "Priya Nair",
    createdAt: "2026-03-30",
    updatedAt: "2026-07-20",
    attachments: [
      {
        id: "ATT-7",
        name: "ERP Migration Business Case.pptx",
        type: "ppt",
        size: "3.4 MB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-07-05",
      },
      {
        id: "ATT-8",
        name: "Legacy System Risk Assessment.pdf",
        type: "pdf",
        size: "1.9 MB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-05-14",
      },
    ],
    comments: [
      {
        id: "CMT-7",
        author: "Priya Nair",
        authorInitials: "PN",
        message:
          "Business case submitted to the Technology Steering Committee for the September budget cycle.",
        createdAt: "2026-07-20",
      },
      {
        id: "CMT-8",
        author: "Layla Haddad",
        authorInitials: "LH",
        message:
          "This needs board visibility given the timeline pressure — adding to next risk committee agenda.",
        createdAt: "2026-07-21",
      },
    ],
    approvals: [
      {
        id: "APR-STEP-4",
        role: "Department Head Approval",
        approver: "Priya Nair",
        status: "approved",
        date: "2026-07-01",
      },
      {
        id: "APR-STEP-5",
        role: "Chief Risk Officer Sign-off",
        approver: "Layla Haddad",
        status: "pending",
      },
    ],
    auditTrail: [
      {
        id: "AUD-19",
        timestamp: "2026-07-21 16:00",
        user: "Layla Haddad",
        action: "Added comment",
        details: "Escalated to risk committee agenda",
      },
      {
        id: "AUD-20",
        timestamp: "2026-07-20 12:30",
        user: "Priya Nair",
        action: "Added comment",
        details: "Business case submitted to steering committee",
      },
      {
        id: "AUD-21",
        timestamp: "2026-07-05 09:15",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "ERP Migration Business Case.pptx",
      },
      {
        id: "AUD-22",
        timestamp: "2026-07-01 11:00",
        user: "Priya Nair",
        action: "Approved workflow step",
        details: "Department Head Approval",
      },
      {
        id: "AUD-23",
        timestamp: "2026-05-14 10:20",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "Legacy System Risk Assessment.pdf",
      },
      {
        id: "AUD-24",
        timestamp: "2026-03-30 08:00",
        user: "Priya Nair",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-6",
        version: 2,
        editedBy: "Priya Nair",
        editedAt: "2026-05-14",
        summary:
          "Added detailed legacy system risk assessment and refreshed controls",
        snapshot: {
          title: "Legacy ERP system end-of-life",
          status: "open",
          likelihood: 5,
          impact: 4,
          inherentRisk: "critical",
        },
      },
      {
        id: "VER-7",
        version: 1,
        editedBy: "Priya Nair",
        editedAt: "2026-03-30",
        summary: "Risk created",
        snapshot: {
          title: "Legacy ERP system end-of-life",
          status: "open",
          likelihood: 5,
          impact: 4,
          inherentRisk: "critical",
        },
      },
    ],
  },
  {
    id: "RSK-1027",
    title: "Talent attrition in engineering leadership",
    department: "Operations",
    category: "Human Capital",
    subcategory: "Talent Attrition",
    rootCause:
      "Below-market compensation bands for senior engineering roles combined with limited succession bench strength.",
    existingControls:
      "Retention bonuses issued to four key leaders; succession plan drafted for the VP Engineering role.",
    inherentRisk: "medium",
    owner: "Omar Farouk",
    likelihood: 3,
    impact: 3,
    status: "mitigating",
    dueDate: "2026-08-25",
    createdBy: "Omar Farouk",
    createdAt: "2026-05-06",
    updatedAt: "2026-07-18",
    attachments: [
      {
        id: "ATT-9",
        name: "Engineering Compensation Benchmark.xlsx",
        type: "xls",
        size: "540 KB",
        uploadedBy: "Omar Farouk",
        uploadedAt: "2026-06-15",
      },
    ],
    comments: [
      {
        id: "CMT-9",
        author: "Omar Farouk",
        authorInitials: "OF",
        message:
          "HR has approved the revised banding; rollout begins next compensation cycle.",
        createdAt: "2026-07-18",
      },
    ],
    approvals: [],
    auditTrail: [
      {
        id: "AUD-25",
        timestamp: "2026-07-18 14:40",
        user: "Omar Farouk",
        action: "Added comment",
        details: "HR approved revised compensation banding",
      },
      {
        id: "AUD-26",
        timestamp: "2026-06-15 10:00",
        user: "Omar Farouk",
        action: "Uploaded attachment",
        details: "Engineering Compensation Benchmark.xlsx",
      },
      {
        id: "AUD-27",
        timestamp: "2026-05-06 08:30",
        user: "Omar Farouk",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-8",
        version: 1,
        editedBy: "Omar Farouk",
        editedAt: "2026-05-06",
        summary: "Risk created",
        snapshot: {
          title: "Talent attrition in engineering leadership",
          status: "mitigating",
          likelihood: 3,
          impact: 3,
          inherentRisk: "medium",
        },
      },
    ],
  },
  {
    id: "RSK-1022",
    title: "Data residency violation in cloud migration",
    department: "Risk & Compliance",
    category: "Compliance",
    subcategory: "Data Privacy",
    rootCause:
      "Cloud migration plan did not initially account for data residency requirements in the EU and KSA.",
    existingControls:
      "Region-locked storage buckets configured; data mapping exercise completed for EU workloads.",
    inherentRisk: "high",
    owner: "Layla Haddad",
    likelihood: 2,
    impact: 5,
    status: "open",
    dueDate: "2026-09-10",
    createdBy: "Layla Haddad",
    createdAt: "2026-05-28",
    updatedAt: "2026-07-15",
    attachments: [
      {
        id: "ATT-10",
        name: "Data Residency Mapping - EU Workloads.pdf",
        type: "pdf",
        size: "980 KB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-07-02",
      },
    ],
    comments: [
      {
        id: "CMT-10",
        author: "Priya Nair",
        authorInitials: "PN",
        message:
          "KSA data mapping is next on the list — targeting completion by end of August.",
        createdAt: "2026-07-15",
      },
    ],
    approvals: [],
    auditTrail: [
      {
        id: "AUD-28",
        timestamp: "2026-07-15 11:20",
        user: "Priya Nair",
        action: "Added comment",
        details: "Update on KSA data mapping timeline",
      },
      {
        id: "AUD-29",
        timestamp: "2026-07-02 09:00",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "Data Residency Mapping - EU Workloads.pdf",
      },
      {
        id: "AUD-30",
        timestamp: "2026-05-28 08:00",
        user: "Layla Haddad",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-9",
        version: 1,
        editedBy: "Layla Haddad",
        editedAt: "2026-05-28",
        summary: "Risk created",
        snapshot: {
          title: "Data residency violation in cloud migration",
          status: "open",
          likelihood: 2,
          impact: 5,
          inherentRisk: "high",
        },
      },
    ],
  },
  {
    id: "RSK-1019",
    title: "Business continuity gap in payment processing",
    department: "Risk & Compliance",
    category: "Operational",
    subcategory: "Business Continuity",
    rootCause:
      "Single data center hosted the payment gateway with no automated failover mechanism.",
    existingControls:
      "Secondary data center failover implemented and tested; recovery time objective reduced to 15 minutes.",
    inherentRisk: "high",
    owner: "Marcus Chen",
    likelihood: 2,
    impact: 4,
    status: "closed",
    dueDate: "2026-07-01",
    createdBy: "Marcus Chen",
    createdAt: "2026-02-14",
    updatedAt: "2026-07-10",
    attachments: [
      {
        id: "ATT-11",
        name: "Failover Test Results - June 2026.pdf",
        type: "pdf",
        size: "1.2 MB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-06-28",
      },
      {
        id: "ATT-12",
        name: "BCP Closure Memo.doc",
        type: "doc",
        size: "310 KB",
        uploadedBy: "Marcus Chen",
        uploadedAt: "2026-07-10",
      },
    ],
    comments: [
      {
        id: "CMT-11",
        author: "Priya Nair",
        authorInitials: "PN",
        message:
          "Failover test completed successfully — RTO of 12 minutes achieved, within target.",
        createdAt: "2026-06-28",
      },
      {
        id: "CMT-12",
        author: "Marcus Chen",
        authorInitials: "MC",
        message: "Closing this out. Great work from the infrastructure team.",
        createdAt: "2026-07-10",
      },
    ],
    approvals: [
      {
        id: "APR-STEP-6",
        role: "Department Head Approval",
        approver: "Priya Nair",
        status: "approved",
        date: "2026-07-02",
      },
      {
        id: "APR-STEP-7",
        role: "Chief Risk Officer Sign-off",
        approver: "Layla Haddad",
        status: "approved",
        date: "2026-07-10",
        comment: "Closure approved based on successful failover testing.",
      },
    ],
    auditTrail: [
      {
        id: "AUD-31",
        timestamp: "2026-07-10 15:00",
        user: "Layla Haddad",
        action: "Approved workflow step",
        details: "Chief Risk Officer Sign-off — risk closed",
      },
      {
        id: "AUD-32",
        timestamp: "2026-07-10 09:30",
        user: "Marcus Chen",
        action: "Updated risk status",
        details: "Status changed from Mitigating to Closed",
      },
      {
        id: "AUD-33",
        timestamp: "2026-07-02 14:00",
        user: "Priya Nair",
        action: "Approved workflow step",
        details: "Department Head Approval",
      },
      {
        id: "AUD-34",
        timestamp: "2026-06-28 16:45",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "Failover Test Results - June 2026.pdf",
      },
      {
        id: "AUD-35",
        timestamp: "2026-02-14 08:00",
        user: "Marcus Chen",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-10",
        version: 2,
        editedBy: "Marcus Chen",
        editedAt: "2026-07-10",
        summary: "Closed following successful failover testing",
        snapshot: {
          title: "Business continuity gap in payment processing",
          status: "closed",
          likelihood: 2,
          impact: 4,
          inherentRisk: "high",
        },
      },
      {
        id: "VER-11",
        version: 1,
        editedBy: "Marcus Chen",
        editedAt: "2026-02-14",
        summary: "Risk created",
        snapshot: {
          title: "Business continuity gap in payment processing",
          status: "open",
          likelihood: 3,
          impact: 4,
          inherentRisk: "high",
        },
      },
    ],
  },
  {
    id: "RSK-1015",
    title: "Insufficient insurance coverage for climate events",
    department: "Finance",
    category: "Financial",
    subcategory: "Insurance Coverage",
    rootCause:
      "Property insurance policy limits have not been reassessed since 2019 despite asset base growth and increased climate event frequency.",
    existingControls:
      "Insurance broker engaged for full policy review; interim coverage increase secured for the flagship facility.",
    inherentRisk: "medium",
    owner: "Daniel Osei",
    likelihood: 2,
    impact: 3,
    status: "open",
    dueDate: "2026-09-20",
    createdBy: "Daniel Osei",
    createdAt: "2026-06-01",
    updatedAt: "2026-07-08",
    attachments: [
      {
        id: "ATT-13",
        name: "Insurance Policy Review - Draft.pdf",
        type: "pdf",
        size: "860 KB",
        uploadedBy: "Daniel Osei",
        uploadedAt: "2026-07-08",
      },
    ],
    comments: [],
    approvals: [],
    auditTrail: [
      {
        id: "AUD-36",
        timestamp: "2026-07-08 10:00",
        user: "Daniel Osei",
        action: "Uploaded attachment",
        details: "Insurance Policy Review - Draft.pdf",
      },
      {
        id: "AUD-37",
        timestamp: "2026-06-01 08:00",
        user: "Daniel Osei",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-12",
        version: 1,
        editedBy: "Daniel Osei",
        editedAt: "2026-06-01",
        summary: "Risk created",
        snapshot: {
          title: "Insufficient insurance coverage for climate events",
          status: "open",
          likelihood: 2,
          impact: 3,
          inherentRisk: "medium",
        },
      },
    ],
  },
  {
    id: "RSK-1011",
    title: "Shadow IT proliferation across business units",
    department: "Technology",
    category: "Technology",
    subcategory: "Shadow IT",
    rootCause:
      "Business units procure SaaS tools directly without IT security review due to a slow central procurement process.",
    existingControls:
      "SaaS discovery tool deployed across the network; expedited security review lane introduced for low-risk tools.",
    inherentRisk: "medium",
    owner: "Priya Nair",
    likelihood: 3,
    impact: 2,
    status: "mitigating",
    dueDate: "2026-08-18",
    createdBy: "Priya Nair",
    createdAt: "2026-04-30",
    updatedAt: "2026-07-04",
    attachments: [
      {
        id: "ATT-14",
        name: "Shadow IT Discovery Report.xlsx",
        type: "xls",
        size: "690 KB",
        uploadedBy: "Priya Nair",
        uploadedAt: "2026-06-10",
      },
    ],
    comments: [
      {
        id: "CMT-13",
        author: "Priya Nair",
        authorInitials: "PN",
        message:
          "47 unsanctioned SaaS tools identified; 12 already brought into the approved catalog.",
        createdAt: "2026-07-04",
      },
    ],
    approvals: [],
    auditTrail: [
      {
        id: "AUD-38",
        timestamp: "2026-07-04 09:00",
        user: "Priya Nair",
        action: "Added comment",
        details: "Update on SaaS discovery remediation",
      },
      {
        id: "AUD-39",
        timestamp: "2026-06-10 13:30",
        user: "Priya Nair",
        action: "Uploaded attachment",
        details: "Shadow IT Discovery Report.xlsx",
      },
      {
        id: "AUD-40",
        timestamp: "2026-04-30 08:00",
        user: "Priya Nair",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-13",
        version: 1,
        editedBy: "Priya Nair",
        editedAt: "2026-04-30",
        summary: "Risk created",
        snapshot: {
          title: "Shadow IT proliferation across business units",
          status: "mitigating",
          likelihood: 3,
          impact: 2,
          inherentRisk: "medium",
        },
      },
    ],
  },
  {
    id: "RSK-1008",
    title: "Anti-bribery and corruption control gaps",
    department: "Internal Audit",
    category: "Compliance",
    subcategory: "Anti-Bribery & Corruption",
    rootCause:
      "Gift and hospitality register not consistently maintained across regional offices.",
    existingControls:
      "Mandatory annual anti-bribery training; gift register digitized and centrally monitored.",
    inherentRisk: "high",
    owner: "Sara Al-Amin",
    likelihood: 1,
    impact: 5,
    status: "open",
    dueDate: "2026-09-05",
    createdBy: "Sara Al-Amin",
    createdAt: "2026-05-20",
    updatedAt: "2026-06-30",
    attachments: [],
    comments: [
      {
        id: "CMT-14",
        author: "Sara Al-Amin",
        authorInitials: "SA",
        message:
          "Regional compliance leads confirmed rollout of the digital gift register in all offices by August.",
        createdAt: "2026-06-30",
      },
    ],
    approvals: [],
    auditTrail: [
      {
        id: "AUD-41",
        timestamp: "2026-06-30 10:30",
        user: "Sara Al-Amin",
        action: "Added comment",
        details: "Confirmed regional rollout timeline",
      },
      {
        id: "AUD-42",
        timestamp: "2026-05-20 08:00",
        user: "Sara Al-Amin",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-14",
        version: 1,
        editedBy: "Sara Al-Amin",
        editedAt: "2026-05-20",
        summary: "Risk created",
        snapshot: {
          title: "Anti-bribery and corruption control gaps",
          status: "open",
          likelihood: 1,
          impact: 5,
          inherentRisk: "high",
        },
      },
    ],
  },
  {
    id: "RSK-1004",
    title: "Customer concentration in top 3 accounts",
    department: "Operations",
    category: "Strategic",
    subcategory: "Customer Concentration",
    rootCause:
      "Top 3 customers represent 46% of annual revenue following two years of organic growth concentration.",
    existingControls:
      "New business development team scaled; diversification target set at board level; concentration reduced to 38%.",
    inherentRisk: "medium",
    owner: "Omar Farouk",
    likelihood: 2,
    impact: 2,
    status: "closed",
    dueDate: "2026-06-15",
    createdBy: "Omar Farouk",
    createdAt: "2026-01-20",
    updatedAt: "2026-06-24",
    attachments: [
      {
        id: "ATT-15",
        name: "Revenue Diversification Progress Report.pdf",
        type: "pdf",
        size: "1.0 MB",
        uploadedBy: "Omar Farouk",
        uploadedAt: "2026-06-20",
      },
    ],
    comments: [
      {
        id: "CMT-15",
        author: "Omar Farouk",
        authorInitials: "OF",
        message:
          "Concentration down to 38% from 46% at start of year — closing as within board-approved tolerance.",
        createdAt: "2026-06-24",
      },
    ],
    approvals: [
      {
        id: "APR-STEP-8",
        role: "Department Head Approval",
        approver: "Sara Al-Amin",
        status: "approved",
        date: "2026-06-22",
      },
      {
        id: "APR-STEP-9",
        role: "Chief Risk Officer Sign-off",
        approver: "Layla Haddad",
        status: "approved",
        date: "2026-06-24",
        comment: "Concentration now within board-approved tolerance.",
      },
    ],
    auditTrail: [
      {
        id: "AUD-43",
        timestamp: "2026-06-24 11:00",
        user: "Layla Haddad",
        action: "Approved workflow step",
        details: "Chief Risk Officer Sign-off — risk closed",
      },
      {
        id: "AUD-44",
        timestamp: "2026-06-24 10:00",
        user: "Omar Farouk",
        action: "Updated risk status",
        details: "Status changed from Mitigating to Closed",
      },
      {
        id: "AUD-45",
        timestamp: "2026-06-22 09:00",
        user: "Sara Al-Amin",
        action: "Approved workflow step",
        details: "Department Head Approval",
      },
      {
        id: "AUD-46",
        timestamp: "2026-06-20 14:15",
        user: "Omar Farouk",
        action: "Uploaded attachment",
        details: "Revenue Diversification Progress Report.pdf",
      },
      {
        id: "AUD-47",
        timestamp: "2026-01-20 08:00",
        user: "Omar Farouk",
        action: "Created risk",
        details: "Risk logged in the register",
      },
    ],
    versions: [
      {
        id: "VER-15",
        version: 2,
        editedBy: "Omar Farouk",
        editedAt: "2026-06-24",
        summary: "Closed after concentration reduced to within tolerance",
        snapshot: {
          title: "Customer concentration in top 3 accounts",
          status: "closed",
          likelihood: 2,
          impact: 2,
          inherentRisk: "medium",
        },
      },
      {
        id: "VER-16",
        version: 1,
        editedBy: "Omar Farouk",
        editedAt: "2026-01-20",
        summary: "Risk created",
        snapshot: {
          title: "Customer concentration in top 3 accounts",
          status: "open",
          likelihood: 3,
          impact: 3,
          inherentRisk: "medium",
        },
      },
    ],
  },
];

export const riskCategoryBreakdown = [
  { label: "Cybersecurity", value: 18 },
  { label: "Compliance", value: 24 },
  { label: "Operational", value: 15 },
  { label: "Financial", value: 12 },
  { label: "Technology", value: 20 },
  { label: "Strategic", value: 8 },
];

export const riskTrend = [
  { label: "Feb", value: 58 },
  { label: "Mar", value: 62 },
  { label: "Apr", value: 55 },
  { label: "May", value: 67 },
  { label: "Jun", value: 71 },
  { label: "Jul", value: 64 },
];
