import type { UserItem } from "@/types";

export const users: UserItem[] = [
  {
    id: "USR-01",
    name: "Layla Haddad",
    email: "layla.haddad@ermcorp.com",
    role: "Chief Risk Officer",
    department: "Risk & Compliance",
    status: "active",
    lastLogin: "2026-07-31 09:14",
  },
  {
    id: "USR-02",
    name: "Marcus Chen",
    email: "marcus.chen@ermcorp.com",
    role: "Compliance Manager",
    department: "Risk & Compliance",
    status: "active",
    lastLogin: "2026-07-31 08:02",
  },
  {
    id: "USR-03",
    name: "Sara Al-Amin",
    email: "sara.alamin@ermcorp.com",
    role: "Internal Audit Lead",
    department: "Internal Audit",
    status: "active",
    lastLogin: "2026-07-30 17:45",
  },
  {
    id: "USR-04",
    name: "Daniel Osei",
    email: "daniel.osei@ermcorp.com",
    role: "Financial Risk Analyst",
    department: "Finance",
    status: "active",
    lastLogin: "2026-07-30 13:21",
  },
  {
    id: "USR-05",
    name: "Priya Nair",
    email: "priya.nair@ermcorp.com",
    role: "IT Risk Manager",
    department: "Technology",
    status: "active",
    lastLogin: "2026-07-31 07:38",
  },
  {
    id: "USR-06",
    name: "Omar Farouk",
    email: "omar.farouk@ermcorp.com",
    role: "Operations Risk Lead",
    department: "Operations",
    status: "inactive",
    lastLogin: "2026-07-11 12:00",
  },
  {
    id: "USR-07",
    name: "Nadia Ibrahim",
    email: "nadia.ibrahim@ermcorp.com",
    role: "Business Analyst",
    department: "Strategy",
    status: "invited",
    lastLogin: "—",
  },
  {
    id: "USR-08",
    name: "Yusuf Karimi",
    email: "yusuf.karimi@ermcorp.com",
    role: "Security Analyst",
    department: "Technology",
    status: "active",
    lastLogin: "2026-07-29 19:12",
  },
];
