import type { VendorItem } from "@/types";

export const vendorItems: VendorItem[] = [
  {
    id: "VEN-6001",
    name: "Nimbus Cloud Infrastructure",
    category: "Cloud & Infrastructure",
    classification: "critical",
    riskRating: "high",
    owner: "Yusuf Karimi",
    contractStart: "2024-01-01",
    contractExpiry: "2026-12-31",
    slaCompliance: 98.4,
    lastDueDiligence: "2026-01-15",
    nextDueDiligence: "2027-01-15",
    assessments: [
      {
        id: "VEN-6001-A1",
        date: "2026-01-15",
        type: "Annual Security Review",
        status: "completed",
        score: 88,
        assessor: "Yusuf Karimi",
      },
      {
        id: "VEN-6001-A2",
        date: "2026-07-01",
        type: "SOC 2 Type II Review",
        status: "in-progress",
        score: 0,
        assessor: "Layla Haddad",
      },
    ],
    incidents: [
      {
        id: "VEN-6001-I1",
        date: "2026-07-21",
        title: "Vendor SLA breach on data center uptime",
        severity: "medium",
      },
    ],
    documents: [
      {
        id: "VEN-6001-D1",
        name: "SOC 2 Type II Report 2025.pdf",
        type: "pdf",
        uploadedAt: "2026-01-10",
        expiresAt: "2027-01-10",
      },
      {
        id: "VEN-6001-D2",
        name: "Master Services Agreement.pdf",
        type: "pdf",
        uploadedAt: "2024-01-01",
        expiresAt: "2026-12-31",
      },
    ],
  },
  {
    id: "VEN-6002",
    name: "Meridian Core Banking Systems",
    category: "Core Banking Software",
    classification: "critical",
    riskRating: "medium",
    owner: "Marcus Chen",
    contractStart: "2022-06-01",
    contractExpiry: "2026-09-30",
    slaCompliance: 99.1,
    lastDueDiligence: "2025-12-01",
    nextDueDiligence: "2026-12-01",
    assessments: [
      {
        id: "VEN-6002-A1",
        date: "2025-12-01",
        type: "Annual Security Review",
        status: "completed",
        score: 91,
        assessor: "Marcus Chen",
      },
    ],
    incidents: [],
    documents: [
      {
        id: "VEN-6002-D1",
        name: "Core Banking Support Contract.pdf",
        type: "pdf",
        uploadedAt: "2022-06-01",
        expiresAt: "2026-09-30",
      },
    ],
  },
  {
    id: "VEN-6003",
    name: "Apex Precision Components",
    category: "Professional Services",
    classification: "high",
    riskRating: "high",
    owner: "Daniel Osei",
    contractStart: "2023-03-01",
    contractExpiry: "2026-08-15",
    slaCompliance: 94.2,
    lastDueDiligence: "2026-03-01",
    nextDueDiligence: "2026-09-01",
    assessments: [
      {
        id: "VEN-6003-A1",
        date: "2026-03-01",
        type: "Supplier Risk Assessment",
        status: "completed",
        score: 74,
        assessor: "Daniel Osei",
      },
    ],
    incidents: [],
    documents: [
      {
        id: "VEN-6003-D1",
        name: "Supply Agreement.pdf",
        type: "pdf",
        uploadedAt: "2023-03-01",
        expiresAt: "2026-08-15",
      },
    ],
  },
  {
    id: "VEN-6004",
    name: "Vantage Payment Processing",
    category: "Payment Processing",
    classification: "critical",
    riskRating: "high",
    owner: "Priya Nair",
    contractStart: "2023-01-01",
    contractExpiry: "2027-01-01",
    slaCompliance: 97.6,
    lastDueDiligence: "2026-04-10",
    nextDueDiligence: "2027-04-10",
    assessments: [
      {
        id: "VEN-6004-A1",
        date: "2026-04-10",
        type: "PCI DSS Compliance Review",
        status: "completed",
        score: 90,
        assessor: "Priya Nair",
      },
    ],
    incidents: [
      {
        id: "VEN-6004-I1",
        date: "2026-07-29",
        title: "Payment gateway outage during peak hours",
        severity: "high",
      },
    ],
    documents: [
      {
        id: "VEN-6004-D1",
        name: "PCI DSS Attestation of Compliance.pdf",
        type: "pdf",
        uploadedAt: "2026-04-10",
        expiresAt: "2027-04-10",
      },
    ],
  },
  {
    id: "VEN-6005",
    name: "Sentinel Facilities & Security",
    category: "Facilities & Security",
    classification: "medium",
    riskRating: "low",
    owner: "Nadia Ibrahim",
    contractStart: "2024-05-01",
    contractExpiry: "2026-08-20",
    slaCompliance: 99.8,
    lastDueDiligence: "2026-05-01",
    nextDueDiligence: "2027-05-01",
    assessments: [
      {
        id: "VEN-6005-A1",
        date: "2026-05-01",
        type: "Vendor Risk Assessment",
        status: "completed",
        score: 95,
        assessor: "Nadia Ibrahim",
      },
    ],
    incidents: [],
    documents: [],
  },
  {
    id: "VEN-6006",
    name: "Bright Horizon Marketing Agency",
    category: "Marketing & Media",
    classification: "low",
    riskRating: "low",
    owner: "Omar Farouk",
    contractStart: "2025-01-01",
    contractExpiry: "2026-12-31",
    slaCompliance: 96.0,
    lastDueDiligence: "2026-01-05",
    nextDueDiligence: "2027-01-05",
    assessments: [],
    incidents: [],
    documents: [],
  },
  {
    id: "VEN-6007",
    name: "Cascade Data Analytics Cloud",
    category: "Cloud & Infrastructure",
    classification: "high",
    riskRating: "medium",
    owner: "Yusuf Karimi",
    contractStart: "2023-09-01",
    contractExpiry: "2026-09-05",
    slaCompliance: 98.9,
    lastDueDiligence: "2025-09-01",
    nextDueDiligence: "2026-09-01",
    assessments: [
      {
        id: "VEN-6007-A1",
        date: "2025-09-01",
        type: "Data Residency Review",
        status: "completed",
        score: 82,
        assessor: "Yusuf Karimi",
      },
      {
        id: "VEN-6007-A2",
        date: "2026-09-01",
        type: "Data Residency Review",
        status: "scheduled",
        score: 0,
        assessor: "Yusuf Karimi",
      },
    ],
    incidents: [],
    documents: [
      {
        id: "VEN-6007-D1",
        name: "Data Processing Addendum.pdf",
        type: "pdf",
        uploadedAt: "2023-09-01",
        expiresAt: null,
      },
    ],
  },
  {
    id: "VEN-6008",
    name: "Fortress Managed Security Services",
    category: "Facilities & Security",
    classification: "critical",
    riskRating: "medium",
    owner: "Yusuf Karimi",
    contractStart: "2024-02-01",
    contractExpiry: "2026-08-01",
    slaCompliance: 97.0,
    lastDueDiligence: "2026-02-01",
    nextDueDiligence: "2026-08-01",
    assessments: [
      {
        id: "VEN-6008-A1",
        date: "2026-02-01",
        type: "Annual Security Review",
        status: "overdue",
        score: 0,
        assessor: "Yusuf Karimi",
      },
    ],
    incidents: [],
    documents: [
      {
        id: "VEN-6008-D1",
        name: "Managed Security Services Agreement.pdf",
        type: "pdf",
        uploadedAt: "2024-02-01",
        expiresAt: "2026-08-01",
      },
    ],
  },
];
